(function (root, factory) {
  const value = factory();
  if (typeof module === "object" && module.exports) module.exports = value;
  root.TempleData = value;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const option = (value, label) => ({ value, label });
  const prediction = (question, correct, labels) => ({ question, correct, options: labels.map(([value, label]) => option(value, label)) });
  const reason = (question, correct, labels) => ({ question, correct, options: labels.map(([value, label]) => option(value, label)) });
  const control = (label, base, target, min, max, step, unit) => ({ label, base, target, min, max, step, unit });
  const input = (id, label, unit, answer, tolerance) => ({ id, label, unit, answer, tolerance });

  const temples = [
    {
      id: "titans", number: "01", eyebrow: "BIOMECHANICS", name: "巨人神殿", short: "生物力學",
      description: "從支點與姿勢建立人體力矩直覺，再以靜力平衡解開巨人的肌肉負荷。",
      heroImage: "assets/titans/biceps.webp", color: "#f6bd4a",
      tracks: {
        foundation: [
          { code: "G-F1", title: "支點之眼", summary: "辨認肘關節、肌肉拉力與石球重力。", mission: "石臂機關只有在三種角色被正確辨認後才會甦醒。", skill: "辨認常見作用力", prerequisites: "讀圖", time: "30–60 秒", image: "assets/titans/biceps.webp", visual: "pivot", known: ["前臂托住石球", "肘關節連接上臂與前臂", "石球受重力向下"], control: control("標記位置", 1, 2, 1, 2, 1, "號"), prediction: prediction("移動標記到肘關節後，它應被判定為哪一種角色？", "pivot", [["pivot","支點"],["effort","施力點"],["load","阻力點"]]), reason: reason("為什麼肘關節是支點？", "rotate", [["rotate","前臂繞它轉動"],["heavy","它最重"],["muscle","它會產生肌力"]]), explanation: "支點是物體轉動所繞的固定位置；在這個模型中，前臂繞肘關節轉動。", hint: "先找出姿勢改變時，哪個位置是旋轉中心。" },
          { code: "G-F2", title: "距離之力", summary: "同樣的力離支點越遠，轉動效果越明顯。", mission: "兩道石門使用相同推力，只有一種施力位置能更輕易轉動門軸。", skill: "比較力臂", prerequisites: "距離比較", time: "30–60 秒", image: "assets/titans/triceps.webp", visual: "lever-distance", known: ["兩次推力大小相同", "推力方向相同", "只改變施力點到支點的距離"], control: control("施力點距離", 10, 30, 10, 30, 5, "cm"), prediction: prediction("把施力點由 10 cm 移到 30 cm，轉動效果會如何？", "increase", [["increase","變大"],["same","不變"],["decrease","變小"]]), reason: reason("哪一項最能解釋觀察結果？", "farther", [["farther","同樣的力離支點更遠"],["mass","手臂質量增加"],["speed","推力速度一定變快"]]), explanation: "力的大小與方向不變時，作用位置離支點越遠，轉動效果越明顯。", hint: "想像推門時，你會推門把還是靠近鉸鏈的位置？" },
          { code: "G-F3", title: "方向之門", summary: "比較沿骨骼與接近垂直的施力方向。", mission: "古代肌索可以改變拉力方向；你要找出最能讓前臂轉動的方向。", skill: "質性判斷力的方向", prerequisites: "辨認夾角", time: "45–75 秒", image: "assets/titans/triceps.webp", visual: "force-direction", known: ["力的大小固定", "施力點固定", "只改變拉力方向"], control: control("拉力與前臂夾角", 15, 90, 15, 90, 15, "°"), prediction: prediction("夾角由 15° 接近 90°，轉動效果通常如何？", "increase", [["increase","變大"],["same","不變"],["decrease","變小"]]), reason: reason("關鍵原因是什麼？", "perpendicular", [["perpendicular","垂直於骨骼的分量變大"],["bone","骨骼會變長"],["weight","石球重量變小"]]), explanation: "同樣大小的力越接近垂直於力臂，越能造成轉動；沿著骨骼拉時多半只造成拉伸或壓縮。", hint: "把力想成可分成沿骨骼與垂直骨骼兩部分。" },
          { code: "G-F4", title: "省力姿勢", summary: "從距離與方向選出較省力的持物姿勢。", mission: "巨人必須搬運石球穿越長廊；選錯姿勢會讓肌肉過早疲勞。", skill: "整合距離與方向", prerequisites: "支點、力的方向", time: "45–90 秒", image: "assets/titans/deadlift.webp", visual: "posture", known: ["石球重量相同", "比較石球靠近與遠離身體", "肌肉必須抵抗石球造成的轉動"], control: control("石球離身體距離", 45, 15, 15, 45, 5, "cm"), prediction: prediction("把石球由離身體 45 cm 收近到 15 cm，肌肉負擔通常如何？", "decrease", [["decrease","減少"],["same","不變"],["increase","增加"]]), reason: reason("最直接的理由是什麼？", "shorter", [["shorter","重力到支點的距離縮短"],["lighter","石球質量變小"],["gravity","重力方向改變"]]), explanation: "把負重靠近支點可縮短重力力臂，因此肌肉需要抵抗的轉動效果較小。", hint: "負重沒有變輕，真正改變的是它到關節的距離。" }
        ],
        advanced: [
          { code: "G-A1", title: "二頭肌之力", summary: "以第三級槓桿求肌肉需要的拉力。", mission: "石球力矩必須由靠近肘部附著的二頭肌平衡。", skill: "力矩平衡", prerequisites: "代數、力矩", time: "60–120 秒", image: "assets/titans/biceps.webp", visual: "biceps", known: ["石球重力 50 N，距肘 30 cm", "二頭肌力臂 5.0 cm", "前臂靜止"], models: [option("balance","F肌 × 5 = 50 × 30"),option("force","F肌 = 50 N"),option("inverse","F肌 × 30 = 50 × 5")], correctModel: "balance", inputs: [input("force","二頭肌拉力","N",300,1)], explanation: "力矩平衡給出 F肌×5 = 50×30，因此二頭肌需提供 300 N。", hint: "支點取在肘關節，先比較肌肉與石球的力臂。" },
          { code: "G-A2", title: "三頭肌之謎", summary: "使用 150° 夾角計算石球重力。", mission: "過頭托球的封印採用畫面幾何：力臂向量與向下重力夾角為 150°。", skill: "τ = rF sinθ", prerequisites: "三角函數、力矩", time: "75–150 秒", image: "assets/titans/triceps.webp", visual: "triceps", known: ["三頭肌拉力 300 N", "三頭肌等效力臂 5.0 cm", "石球距肘 30 cm", "力臂向量與重力夾角 150°"], models: [option("sine","300×5 = W×30×sin150°"),option("cosine","300×5 = W×30×cos150°"),option("noangle","300×5 = W×30")], correctModel: "sine", inputs: [input("weight","石球重力","N",100,1)], explanation: "sin150°=0.5；300×5 = W×30×0.5，所以 W=100 N。", hint: "力矩使用力臂向量與力的夾角；sin150° 等於 sin30°。" },
          { code: "G-A3", title: "硬舉之重", summary: "整合上半身、石球與髖伸肌的多力矩平衡。", mission: "髖關節封印同時承受軀幹與石輪兩個外力矩。", skill: "多力矩平衡", prerequisites: "代數、力矩加總", time: "90–180 秒", image: "assets/titans/deadlift.webp", visual: "deadlift", known: ["上半身重力 300 N，力臂 40 cm", "石球重力 W，力臂 60 cm", "髖肌力 2250 N，力臂 8 cm"], models: [option("sum","2250×8 = 300×40 + W×60"),option("single","2250×8 = W×60"),option("subtract","2250×8 + 300×40 = W×60")], correctModel: "sum", inputs: [input("weight","石球重力","N",100,1)], explanation: "髖肌力矩 18000 N·cm 必須同時平衡軀幹 12000 N·cm 與石球力矩，因此 W=100 N。", hint: "不要漏掉上半身重量，它與石球對髖部造成同方向力矩。" },
          { code: "G-A4", title: "阿基里斯之踵", summary: "分解肌腱力並完成足部靜力平衡。", mission: "踮腳機關只有在阿基里斯腱對前腳掌支點的有效力矩正確時才會開啟。", skill: "分力與靜力平衡", prerequisites: "三角函數、力矩", time: "90–180 秒", image: "assets/titans/achilles.webp", visual: "achilles", known: ["肌腱張力 3000 N", "肌腱與腳板夾角 120°", "肌腱距前腳掌支點 1.0 cm", "身體重力作用線距支點 20 cm"], models: [option("perp","3000×sin120°×1 = W×20"),option("full","3000×1 = W×20"),option("cos","3000×cos120°×1 = W×20")], correctModel: "perp", inputs: [input("weight","身體重力","N",130,2)], explanation: "肌腱垂直分量約 2598 N；以足尖為支點平衡後 W≈2598/20≈130 N。", hint: "只有垂直於腳板的肌腱分量產生有效力矩。" }
        ]
      }
    },
    {
      id: "chrono", number: "02", eyebrow: "MOTION & GRAPHS", name: "時空軌跡修復者", short: "運動學",
      description: "從位置—時間圖判斷速度與相遇，再以運動方程修復追擊與煞車事件。",
      heroImage: "assets/chrono/time-1.webp", color: "#64d9ff",
      tracks: {
        foundation: [
          { code:"C-F1",title:"誰跑得快",summary:"位置—時間圖越陡，物體運動越快。",mission:"兩列時空列車留下不同斜率的軌跡；判斷哪一列更快。",skill:"判讀位置—時間圖",prerequisites:"座標圖",time:"30–60 秒",image:"assets/chrono/time-1.webp",visual:"xt-slope",known:["橫軸為時間","縱軸為位置","比較相同時間內位置改變"],control:control("青色軌跡陡峭度",1,3,1,3,1,"級"),prediction:prediction("青色軌跡變得更陡時，青色列車的速度如何？","increase",[["increase","變快"],["same","不變"],["decrease","變慢"]]),reason:reason("圖像證據是什麼？","more-position",[["more-position","相同時間內位置改變更多"],["higher","線畫得比較高所以質量大"],["color","青色代表高速"]]),explanation:"位置—時間圖的斜率代表速度；相同時間內位置改變越多，線越陡、速度越大。",hint:"固定一段相同的時間，比較兩條線上升多少。"},
          { code:"C-F2",title:"相遇之兆",summary:"兩條位置—時間軌跡的交點代表同時同地。",mission:"找出兩列車在時空圖上真正會合的訊號。",skill:"辨認圖線交點",prerequisites:"座標圖",time:"30–60 秒",image:"assets/chrono/time-2.webp",visual:"xt-meet",known:["兩條線描述兩列車的位置","同一橫座標代表同一時間","同一縱座標代表同一位置"],control:control("觀察時間",0,6,0,6,1,"s"),prediction:prediction("觀察時間移到兩條線交點時，兩列車發生什麼事？","meet",[["meet","同時到達同一位置"],["speed","速度一定相同"],["stop","同時停止"]]),reason:reason("為什麼交點表示相遇？","same-coordinates",[["same-coordinates","時間與位置座標都相同"],["same-slope","兩線斜率永遠相同"],["same-color","兩線顏色接近"]]),explanation:"圖線交點的橫、縱座標同時相同，代表兩物體在同一時刻位於同一位置。",hint:"相遇需要同時滿足『同一時間』與『同一位置』。"},
          { code:"C-F3",title:"追擊預言",summary:"後車速度必須較大，才可能縮短領先距離。",mission:"橙車已先行，青車必須選擇能逐漸追近的速度狀態。",skill:"質性相對運動",prerequisites:"快慢比較",time:"45–75 秒",image:"assets/chrono/time-3.webp",visual:"chase",known:["橙車在前方","兩車同方向","青車從後方追趕"],control:control("青車相對速度",0,2,0,2,1,"級"),prediction:prediction("當青車比橙車更快時，兩車距離如何變化？","decrease",[["decrease","逐漸縮短"],["same","保持不變"],["increase","逐漸增加"]]),reason:reason("關鍵原因是什麼？","relative",[["relative","後車每秒前進得更多"],["front","前車一定會停下"],["mass","後車質量較大"]]),explanation:"同方向運動時，後車速度較大才具有正的追近速度，兩車間距會逐漸縮短。",hint:"每經過一秒，比較兩車各自前進的距離。"},
          { code:"C-F4",title:"煞車曲線",summary:"辨認速度下降、停止與越過星門的圖像特徵。",mission:"列車必須在星門前讓速度降到零；選出正確的速度—時間軌跡。",skill:"判讀速度—時間圖",prerequisites:"圖形趨勢",time:"45–90 秒",image:"assets/chrono/time-4.webp",visual:"brake",known:["橫軸為時間","縱軸為速度","速度降到 0 代表停止"],control:control("煞車強度",1,3,1,3,1,"級"),prediction:prediction("煞車變強時，速度降到 0 所需時間如何？","decrease",[["decrease","縮短"],["same","不變"],["increase","拉長"]]),reason:reason("在速度—時間圖上會看到什麼？","steeper-down",[["steeper-down","下降線更陡並較早碰到 0"],["up","線向上升"],["flat","線保持水平"]]),explanation:"較強煞車使速度下降更快，因此速度—時間線向下更陡，也更早到達零。",hint:"先找出圖上代表停止的 v=0 水平軸。"}
        ],
        advanced: [
          { code:"C-A1",title:"等速會合",summary:"由距離與時間求維持會合所需速度。",mission:"青車必須在 20 秒後抵達 120 公尺外的事件點。",skill:"等速運動",prerequisites:"v=Δx/Δt",time:"60–100 秒",image:"assets/chrono/time-1.webp",visual:"chrono-uniform",known:["位移 120 m","允許時間 20 s","等速直線運動"],models:[option("uniform","v = Δx / Δt"),option("accel","Δx = ½at²"),option("momentum","p = mv")],correctModel:"uniform",inputs:[input("speed","列車速度","m/s",6,.05)],explanation:"v=120/20=6 m/s。",hint:"題目沒有加速資訊，使用等速位移關係。"},
          { code:"C-A2",title:"加速會合",summary:"由靜止出發的位移與時間求加速度。",mission:"青車由靜止穿越 100 公尺長的加速環廊，必須在 10 秒抵達。",skill:"等加速度",prerequisites:"x=v₀t+½at²",time:"75–130 秒",image:"assets/chrono/time-2.webp",visual:"chrono-accel",known:["初速 0 m/s","位移 100 m","時間 10 s","加速度固定"],models:[option("accel","x = ½at²"),option("uniform","x = vt"),option("energy","v² = 2ax，直接令 v=10")],correctModel:"accel",inputs:[input("acceleration","加速度","m/s²",2,.03)],explanation:"100=½×a×10²，所以 a=2 m/s²。",hint:"由靜止出發，初速項為零。"},
          { code:"C-A3",title:"延遲追擊",summary:"使用相對速度處理先行與延遲。",mission:"橙車以 4 m/s 先行 10 秒，青車再以 8 m/s 出發。",skill:"相對速度",prerequisites:"等速、代數",time:"75–140 秒",image:"assets/chrono/time-3.webp",visual:"chrono-delay",known:["橙車速度 4 m/s","橙車先行 10 s","青車速度 8 m/s"],models:[option("relative","t = 先行距離 / (8−4)"),option("sum","t = 先行距離 / (8+4)"),option("ignore","t = 先行距離 / 8")],correctModel:"relative",inputs:[input("time","青車出發後追上時間","s",10,.1)],explanation:"橙車先行 40 m，追近速度為 4 m/s，所以需 10 s。",hint:"先算領先距離，再用兩車速度差求追近時間。"},
          { code:"C-A4",title:"煞車收束",summary:"由初速與加速度求停止距離。",mission:"列車以 20 m/s 進入星門廊，固定減速度為 4 m/s²。",skill:"等加速度煞停",prerequisites:"v²=v₀²+2aΔx",time:"75–140 秒",image:"assets/chrono/time-4.webp",visual:"chrono-stop",known:["初速 20 m/s","末速 0 m/s","加速度 −4 m/s²"],models:[option("v2","0 = 20² + 2(−4)Δx"),option("linear","0 = 20 − 4Δx"),option("uniform","Δx = 20×4")],correctModel:"v2",inputs:[input("distance","煞停距離","m",50,.2)],explanation:"0=400−8Δx，因此煞停距離為 50 m。",hint:"時間未知，可選不含時間的等加速度公式。"}
        ]
      }
    },
    {
      id:"photo",number:"03",eyebrow:"PHOTOELECTRIC EFFECT",name:"古光神殿",short:"近代物理",description:"先破解頻率門檻與亮度迷思，再計算光子能量、截止電壓與粒子數。",heroImage:"assets/photo/light-1.webp",color:"#76a9ff",
      tracks:{
        foundation:[
          {code:"P-F1",title:"頻率門檻",summary:"頻率增加，單一光子能量增加。",mission:"調高光的頻率，判斷何時能越過金屬功函數門檻。",skill:"E 與 f 的比例",prerequisites:"比例概念",time:"30–60 秒",image:"assets/photo/light-1.webp",visual:"photo-threshold",known:["同一金屬的門檻固定","光子能量隨頻率增加","先不計算數值"],control:control("光的頻率",2,4,2,4,1,"級"),prediction:prediction("把頻率由低調高，單一光子能量如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("能打出電子的必要條件是什麼？","threshold",[["threshold","單一光子能量超過功函數"],["bright","光只要夠亮"],["time","照射時間夠久一定可以"]]),explanation:"光電效應有頻率門檻；單一光子能量不足時，增加等待時間也不能把能量累積給同一電子。",hint:"關鍵是『每一顆光子』的能量，而不是總共有多少光。"},
          {code:"P-F2",title:"亮度迷霧",summary:"頻率不足時，再強的光也不能打出電子。",mission:"古光祭壇故意以極亮紅光誤導闖關者。",skill:"區分頻率與強度",prerequisites:"光子概念",time:"45–75 秒",image:"assets/photo/light-2.webp",visual:"photo-intensity",known:["光的頻率低於金屬門檻","只提高光強度","金屬種類不變"],control:control("光強度",1,5,1,5,1,"級"),prediction:prediction("頻率仍低於門檻，只把光變強，會打出電子嗎？","no",[["no","不會"],["yes","一定會"],["faster","只會讓電子更快"]]),reason:reason("為什麼？","per-photon",[["per-photon","每顆光子的能量仍不足"],["metal","金屬突然變重"],["voltage","電壓自動抵消"]]),explanation:"強度增加代表光子數增加，但每顆光子的能量由頻率決定；低於門檻仍無法逸出。",hint:"把強度想成光子『數量』，頻率想成每顆光子的『能量』。"},
          {code:"P-F3",title:"金屬之別",summary:"不同金屬具有不同的光電門檻。",mission:"用同一束光照射兩塊金屬，從實驗結果判斷哪一塊功函數較小。",skill:"由證據比較門檻",prerequisites:"控制變因",time:"45–75 秒",image:"assets/photo/light-3.webp",visual:"photo-metal",known:["照射頻率相同","A 金屬放出電子","B 金屬沒有放出電子"],control:control("照射測試",1,2,1,2,1,"次"),prediction:prediction("根據結果，哪一塊金屬較容易放出電子？","A",[["A","A 金屬"],["B","B 金屬"],["same","無法區分"]]),reason:reason("可以做出什麼判斷？","lower",[["lower","A 的功函數較小"],["higher","A 的功函數較大"],["mass","A 的質量較小"]]),explanation:"同頻率光下，能放出電子的 A 金屬門檻不高於該光子能量，因此相較 B 更容易放出電子。",hint:"控制相同照射條件，比較哪個金屬先產生反應。"},
          {code:"P-F4",title:"有限光能",summary:"選擇剛好越過門檻的頻率並合理分配強度。",mission:"三道光門共享有限能量；過低頻率無效，過高設定又浪費資源。",skill:"質性策略",prerequisites:"頻率門檻、強度",time:"60–90 秒",image:"assets/photo/light-4.webp",visual:"photo-budget",known:["三座金屬門檻不同","頻率必須先超過門檻","門檻已通過後，提高強度可增加電子數"],control:control("頻率設定",2,4,2,5,1,"級"),prediction:prediction("有限資源下，合理的第一步是什麼？","threshold-first",[["threshold-first","先選剛能越過門檻的頻率"],["intensity-only","全部能量只加強度"],["max","頻率與強度永遠都開最大"]]),reason:reason("越過門檻後，若需要更多電子應優先調整什麼？","intensity",[["intensity","增加光強度"],["lower-frequency","把頻率降回門檻以下"],["wait","只增加等待時間"]]),explanation:"策略是先確保單一光子能量足夠，再用強度控制有效光子數；這能把頻率與強度的角色分開。",hint:"先問『能不能打出』，再問『能打出多少』。"}
        ],
        advanced:[
          {code:"P-A1",title:"光子換算",summary:"由波長求單一光子能量。",mission:"藍光封印給定波長 400 nm，需換算成電子伏特。",skill:"E=hc/λ",prerequisites:"科學記號、單位換算",time:"60–120 秒",image:"assets/photo/light-1.webp",visual:"photo-energy",known:["λ=400 nm","可用 hc≈1240 eV·nm"],models:[option("lambda","E=1240/λ"),option("multiply","E=1240λ"),option("intensity","E=P×t")],correctModel:"lambda",inputs:[input("energy","光子能量","eV",3.10,.03)],explanation:"E≈1240/400=3.10 eV。",hint:"波長越短，單一光子能量越高。"},
          {code:"P-A2",title:"最大動能",summary:"由光子能量扣除金屬功函數。",mission:"能量 3.5 eV 的光子照射功函數 2.3 eV 的鈉。",skill:"光電方程",prerequisites:"能量守恆",time:"60–120 秒",image:"assets/photo/light-2.webp",visual:"photo-kmax",known:["Eγ=3.5 eV","Φ=2.3 eV","忽略其他損失"],models:[option("subtract","Kmax=Eγ−Φ"),option("add","Kmax=Eγ+Φ"),option("ratio","Kmax=Eγ/Φ")],correctModel:"subtract",inputs:[input("kmax","最大動能","eV",1.2,.02)],explanation:"Kmax=3.5−2.3=1.2 eV。",hint:"功函數是電子離開金屬表面必須支付的能量。"},
          {code:"P-A3",title:"截止電壓",summary:"由最大動能求停止光電子的電壓。",mission:"光電子最大動能為 1.4 eV，調整反向電壓剛好讓光電流歸零。",skill:"eVₛ=Kmax",prerequisites:"電位能、光電方程",time:"60–120 秒",image:"assets/photo/light-3.webp",visual:"photo-voltage",known:["Kmax=1.4 eV","1 eV 對應電子通過 1 V 的能量"],models:[option("stopping","eVₛ=Kmax"),option("square","eVₛ²=Kmax"),option("power","Vₛ=Kmax×光強")],correctModel:"stopping",inputs:[input("voltage","截止電壓","V",1.4,.02)],explanation:"以 eV 為能量單位時，1.4 eV 對應 1.4 V 的截止電壓。",hint:"截止電壓與最大動能有關，不由光強度決定。"},
          {code:"P-A4",title:"光束配給",summary:"計算光子流率、量子效率與有效電子數。",mission:"20 W 光束照射 2 秒；教學模型設定每瓦每秒 10 顆光子、量子效率 25%。",skill:"率與效率",prerequisites:"比例、百分率",time:"75–150 秒",image:"assets/photo/light-4.webp",visual:"photo-flux",known:["20 W","每 W 每秒 10 顆光子","照射 2 s","量子效率 25%"],models:[option("flux","Ne=P×10×t×η"),option("divide","Ne=P/(10tη)"),option("energy","Ne=光子能量−功函數")],correctModel:"flux",inputs:[input("electrons","有效電子數","顆",100,1)],explanation:"20×10×2×0.25=100 顆有效電子。這是明確標示的教學縮放模型。",hint:"先求入射光子總數，再乘量子效率。"}
        ]
      }
    },
    {
      id:"ripple",number:"04",eyebrow:"WAVES & INTERFERENCE",name:"水之神殿",short:"波動",description:"用可操作水面建立頻率、波長與振幅直覺，再進入相位、程差與節腹線計算。",heroImage:"assets/ripple/water-1.webp",color:"#55e2db",
      tracks:{
        foundation:[
          {code:"W-F1",title:"水之節奏",summary:"頻率變大時，波長變短、條紋變窄。",mission:"調高水眼振動頻率，預測同心波紋會如何改變。",skill:"頻率與波長質性關係",prerequisites:"讀圖、反比趨勢",time:"30–60 秒",image:"assets/ripple/water-1.webp",visual:"wave-frequency",known:["水波速度固定","單一波源","頻率由 2 Hz 調到 4 Hz"],control:control("頻率",2,4,1,5,.5,"Hz"),prediction:prediction("頻率由 2 Hz 增加到 4 Hz，環形條紋如何變化？","narrow",[["narrow","變窄、變密"],["same","不變"],["wide","變寬、變疏"]]),reason:reason("哪一個因果鏈正確？","inverse",[["inverse","波速固定，f 增加所以 λ 減少"],["amplitude","頻率增加所以振幅必定增加"],["speed","頻率增加所以水波速度必定增加"]]),explanation:"在同一介質且波速固定時，v=fλ；頻率增加，波長縮短，所以條紋變密。",hint:"固定波速，把 f 與 λ 看成互相補償的兩個量。"},
          {code:"W-F2",title:"振幅幻象",summary:"振幅增大會加強起伏與對比，但不改變波長。",mission:"提高水眼振幅，分辨『看起來更強』與『條紋間距改變』。",skill:"區分振幅與波長",prerequisites:"波形判讀",time:"30–60 秒",image:"assets/ripple/water-2.webp",visual:"wave-amplitude",known:["頻率固定","水波速度固定","振幅由 1 級增至 3 級"],control:control("振幅",1,3,1,3,.5,"級"),prediction:prediction("振幅增加後，波紋主要如何改變？","contrast",[["contrast","起伏與明暗對比變強"],["narrow","波長變短"],["faster","傳播速度必定增加"]]),reason:reason("為什麼條紋間距不變？","frequency",[["frequency","頻率與波速都沒改變"],["source","波源消失了"],["mass","水的質量變成零"]]),explanation:"振幅描述偏離平衡位置的程度；只改振幅不會改變由波速與頻率決定的波長。",hint:"把『波有多高』與『相鄰波峰隔多遠』分開看。"},
          {code:"W-F3",title:"雙源初醒",summary:"兩個同頻波源產生穩定的加強區與削弱區。",mission:"喚醒第二座水眼，觀察兩組波疊加後出現的新結構。",skill:"辨認干涉現象",prerequisites:"波的疊加概念",time:"45–75 秒",image:"assets/ripple/water-3.webp",visual:"wave-two-source",known:["兩波源頻率相同","兩波源持續振動","不計算相位差"],control:control("波源數量",1,2,1,2,1,"個"),prediction:prediction("由一個波源改成兩個同頻波源，水面會出現什麼？","bands",[["bands","穩定的加強與削弱區"],["nothing","完全沒有變化"],["stop","所有水波都消失"]]),reason:reason("這些區域形成的原因是什麼？","superpose",[["superpose","兩列波在各處疊加"],["gravity","重力忽然改變"],["boil","水溫升高"]]),explanation:"兩列同頻波重疊後，在不同位置持續加強或削弱，形成穩定干涉圖樣。",hint:"觀察哪些位置總是明顯起伏，哪些位置長期接近平靜。"},
          {code:"W-F4",title:"雙源之謎",summary:"波源間距增加時，節線與腹線分布通常變密。",mission:"頻率固定，只拉開兩座水眼，匹配更密集的干涉骨架。",skill:"波源間距與圖樣",prerequisites:"干涉現象",time:"45–90 秒",image:"assets/ripple/water-4.webp",visual:"wave-separation",known:["頻率固定","兩波源同頻","間距由 4 格增至 8 格"],control:control("波源間距",4,8,3,10,.5,"格"),prediction:prediction("波源距離增加後，節線／腹線分布通常如何？","denser",[["denser","變得較密"],["same","完全不變"],["none","全部消失"]]),reason:reason("同時有哪一項保持不變？","wavelength",[["wavelength","單一波源的波長"],["geometry","干涉圖幾何"],["source-distance","波源距離"]]),explanation:"頻率與介質不變，所以單一波源波長不變；增加波源間距則讓可出現的程差範圍變大，干涉線數通常增加。",hint:"分開觀察『每一圈的間距』與『兩組圓相交形成的骨架』。"}
        ],
        advanced:[
          {code:"W-A1",title:"波速石碑",summary:"使用 v=fλ 求波速。",mission:"水眼頻率為 6 Hz，相鄰波峰距離為 0.50 m。",skill:"v=fλ",prerequisites:"代數、單位",time:"60–100 秒",image:"assets/ripple/water-1.webp",visual:"wave-calc",known:["f=6 Hz","λ=0.50 m"],models:[option("wave","v=fλ"),option("divide","v=f/λ"),option("square","v=fλ²")],correctModel:"wave",inputs:[input("speed","波速","m/s",3,.03)],explanation:"v=6×0.50=3.0 m/s。",hint:"Hz 是每秒振動次數，乘上一個波長就是每秒傳播距離。"},
          {code:"W-A2",title:"相位與程差之門",summary:"由程差判斷相對相位與破壞性干涉。",mission:"某觀測點到兩個同相波源的程差為 1.5λ。",skill:"程差與相位",prerequisites:"相位、波的疊加",time:"75–140 秒",image:"assets/ripple/water-2.webp",visual:"wave-phase",known:["兩波源同相","Δr=1.5λ","相位差以 360° 為一週期"],models:[option("phase","Δφ=360°×Δr/λ"),option("linear","Δφ=180°×Δr/λ"),option("none","程差不影響相位")],correctModel:"phase",inputs:[input("phase","等效相位差","°",180,1)],explanation:"1.5λ 對應 540°，扣除一個 360° 週期後為 180°，因此為破壞性干涉。",hint:"相位差可相差整數個 360°；最後取等效角。"},
          {code:"W-A3",title:"節腹線計數",summary:"由 d/λ 計算完整平面的節線與腹線。",mission:"兩個同相點波源間距 d=3.2λ；計算左右兩側都包含的完整圖樣。",skill:"干涉線階數",prerequisites:"程差、取整數",time:"90–160 秒",image:"assets/ripple/water-3.webp",visual:"wave-lines",known:["d/λ=3.2","波源同相","計完整平面、左右對稱線都算","非整數與半整數邊界"],models:[option("count","腹線 2⌊d/λ⌋+1；節線 2⌊d/λ+1/2⌋"),option("swap","腹線 2⌊d/λ+1/2⌋；節線 2⌊d/λ⌋+1"),option("round","兩者都取最接近整數")],correctModel:"count",inputs:[input("antinodes","腹線條數","條",7,0),input("nodes","節線條數","條",6,0)],explanation:"腹線階數 m=0,±1,±2,±3，共 7 條；節線程差 0.5λ、1.5λ、2.5λ，各有左右兩側，共 6 條。",hint:"先列出允許的程差階數，再把中央線與左右對稱分開計數。"},
          {code:"W-A4",title:"干涉核心",summary:"從圖形證據反推頻率與中央相位。",mission:"水波速度 12 cm/s，圖上相鄰波峰距離 4 cm，中央線為節線。",skill:"反推多個參數",prerequisites:"v=fλ、相位",time:"90–180 秒",image:"assets/ripple/water-4.webp",visual:"wave-inverse",known:["v=12 cm/s","λ=4 cm","兩波源振幅相同","中央線為節線"],models:[option("inverse","f=v/λ，中央節線代表兩源反相"),option("multiply","f=vλ，中央節線代表同相"),option("amplitude","f 由振幅決定")],correctModel:"inverse",inputs:[input("frequency","頻率","Hz",3,.03),input("phase","兩源相位差","°",180,1)],explanation:"f=12/4=3 Hz；中央點到兩源等距，卻是節線，表示兩源相差 180°。",hint:"中央線程差為零；若仍相消，差異只能來自波源初相位。"}
        ]
      }
    },
    {
      id:"uncertainty",number:"05",eyebrow:"MEASUREMENT & EVIDENCE",name:"不確定度神殿",short:"實驗與量測",description:"從刻度、散布與誠實紀錄建立量測素養，再完成組合不確定度與導出量證據鏈。",heroImage:"assets/uncertainty/measure-1.webp",color:"#c3a6ff",
      tracks:{
        foundation:[
          {code:"U-F1",title:"刻度之眼",summary:"讀取儀器數值、單位與最小刻度。",mission:"電子秤穩定顯示 63 g；不要宣稱儀器沒有提供的位數。",skill:"儀器判讀",prerequisites:"單位",time:"30–60 秒",image:"assets/uncertainty/measure-1.webp",visual:"measure-scale",known:["電子秤顯示 63 g","最小顯示單位 1 g","多次讀值相同"],control:control("顯示位數",0,1,0,2,1,"級"),prediction:prediction("哪一筆直接讀值最恰當？","63g",[["63g","63 g"],["63.000g","63.000 g"],["about","約 60 g"]]),reason:reason("為什麼不能寫成 63.000 g？","digits",[["digits","儀器沒有提供那些小數位"],["mass","木塊太輕"],["unit","g 不是單位"]]),explanation:"紀錄應保留儀器實際提供的位數與單位；多寫小數會過度宣稱精度。",hint:"螢幕上實際出現了幾位數？"},
          {code:"U-F2",title:"重複回聲",summary:"量測散布不等於實驗失敗。",mission:"比較兩組重複量測，判斷哪一組的重複性較好。",skill:"辨認散布",prerequisites:"大小比較",time:"30–60 秒",image:"assets/uncertainty/measure-2.webp",visual:"measure-scatter",known:["A 組：25.6、25.6、25.7、25.6","B 組：25.1、25.8、25.4、26.0","使用同一單位"],control:control("顯示資料組",1,2,1,2,1,"組"),prediction:prediction("哪一組量測結果較集中？","A",[["A","A 組"],["B","B 組"],["same","兩組完全相同"]]),reason:reason("較集中的結果代表什麼？","repeatability",[["repeatability","重複性較好"],["truth","一定等於真值"],["zero","不確定度必定為零"]]),explanation:"散布較小表示在相同條件下重複性較好，但仍不能單憑集中就保證沒有系統誤差。",hint:"比較每組最大值與最小值相差多少。"},
          {code:"U-F3",title:"哪把尺更適合",summary:"依任務需求選擇合適的最小刻度。",mission:"要量測約 25.6 mm 的小銅柱，選擇公分尺或 0.1 mm 游標尺。",skill:"選擇量具",prerequisites:"刻度與單位",time:"30–60 秒",image:"assets/uncertainty/measure-3.webp",visual:"measure-tool",known:["需要分辨約 0.1 mm 的差異","公分尺最小刻度 1 mm","游標尺可讀到 0.1 mm"],control:control("所需解析度",1,2,1,2,1,"級"),prediction:prediction("哪一件量具較符合任務？","caliper",[["caliper","0.1 mm 游標尺"],["ruler","1 mm 公分尺"],["either","兩者完全相同"]]),reason:reason("選擇依據是什麼？","resolution",[["resolution","最小刻度能分辨所需差異"],["color","量具顏色較深"],["length","量具本身較重"]]),explanation:"量具解析度必須足以分辨任務關心的差異；更細刻度不代表永遠更好，但此任務確實需要 0.1 mm。",hint:"先問你希望分辨到多小，再比較儀器刻度。"},
          {code:"U-F4",title:"誠實的數字",summary:"選出不過度宣稱精度的量測報告。",mission:"平均高度約 25.625 mm，估計不確定度約 0.09 mm；選出位數一致的表達。",skill:"量測結果表達",prerequisites:"小數位",time:"45–75 秒",image:"assets/uncertainty/measure-4.webp",visual:"measure-report",known:["平均值計算結果 25.625 mm","不確定度約 0.09 mm","數值與不確定度小數位應一致"],control:control("報告格式",1,2,1,2,1,"式"),prediction:prediction("哪一種寫法最合適？","honest",[["honest","(25.63 ± 0.09) mm"],["precise","(25.625000 ± 0.09) mm"],["rough","(26 ± 0.0001) mm"]]),reason:reason("為什麼平均值寫到小數點後兩位？","place",[["place","與不確定度的末位對齊"],["pretty","看起來比較整齊"],["unit","因為 mm 只能有兩位"]]),explanation:"測量值與不確定度的末位應對齊，避免保留沒有意義的額外數字。",hint:"先看不確定度最後一位落在哪個小數位。"}
        ],
        advanced:[
          {code:"U-A1",title:"質量的密碼",summary:"由電子秤最小顯示單位估計 B 類標準不確定度。",mission:"電子秤顯示 63 g，最小顯示單位為 1 g，採均勻分布模型。",skill:"B 類不確定度",prerequisites:"有效數字、平方根",time:"75–130 秒",image:"assets/uncertainty/measure-1.webp",visual:"uncertainty-mass",known:["讀值 63 g","最小顯示單位 1 g","uB=LC/√12"],models:[option("rect","uB=1/√12"),option("half","uB=1/2"),option("zero","重複相同所以 u=0")],correctModel:"rect",inputs:[input("uncertainty","標準不確定度","g",.29,.015)],explanation:"uB=1/√12≈0.29 g；重複顯示相同不代表儀器解析度造成的不確定度為零。",hint:"數位顯示採寬度為一個最小顯示單位的均勻分布。"},
          {code:"U-A2",title:"三維尺寸",summary:"把尺的解析度轉成長度標準不確定度。",mission:"以最小刻度 0.1 cm 的量具量得長度 10.0 cm。",skill:"儀器不確定度",prerequisites:"B 類不確定度",time:"60–120 秒",image:"assets/uncertainty/measure-2.webp",visual:"uncertainty-dimension",known:["L=10.0 cm","最小刻度 0.1 cm","採均勻分布"],models:[option("rect","uL=0.1/√12"),option("full","uL=0.1"),option("percent","uL=10%")],correctModel:"rect",inputs:[input("uncertainty","長度標準不確定度","cm",.029,.002)],explanation:"uL=0.1/√12≈0.029 cm。",hint:"先確認公式中的 LC 使用和答案相同的 cm 單位。"},
          {code:"U-A3",title:"周長迴廊",summary:"處理加減與常數倍的不確定度傳遞。",mission:"矩形長 10.0±0.03 cm、寬 5.0±0.03 cm，求 P=2(L+W) 的標準不確定度。",skill:"加減法傳遞",prerequisites:"平方和開根號",time:"90–160 秒",image:"assets/uncertainty/measure-3.webp",visual:"uncertainty-perimeter",known:["uL=0.03 cm","uW=0.03 cm","L、W 獨立","P=2(L+W)"],models:[option("rss","uP=2√(uL²+uW²)"),option("linear","uP=2(uL+uW)"),option("relative","uP/P=uL/L+uW/W")],correctModel:"rss",inputs:[input("uncertainty","周長標準不確定度","cm",.085,.004)],explanation:"uP=2√(0.03²+0.03²)≈0.085 cm。",hint:"獨立不確定度先平方相加，再開根號；外面的常數 2 一起乘上。"},
          {code:"U-A4",title:"體積與密度核心",summary:"使用相對不確定度傳遞處理乘除。",mission:"木塊 10.0×5.0×2.0 cm，各邊 u=0.03 cm；質量 270 g，um=0.29 g。",skill:"導出量不確定度",prerequisites:"相對不確定度、平方和",time:"120–180 秒",image:"assets/uncertainty/measure-4.webp",visual:"uncertainty-density",known:["V=LWH","ρ=m/V","各來源獨立","標準不確定度以平方和組合"],models:[option("relative","(uρ/ρ)²=(um/m)²+(uV/V)²"),option("absolute","uρ=um−uV"),option("linear","uρ/ρ=um/m+uL/L+uW/W+uH/H")],correctModel:"relative",inputs:[input("density","密度","g/cm³",2.70,.015),input("uncertainty","密度標準不確定度","g/cm³",.045,.004)],explanation:"V=100 cm³，ρ=2.70 g/cm³；組合各相對不確定度後 uρ≈0.045 g/cm³。",hint:"乘除問題先把每個來源換成相對不確定度，再用平方和組合。"},
          {code:"U-A5",title:"銅柱回聲",summary:"組合重複量測 A 類與儀器 B 類不確定度。",mission:"四次高度為 25.40、25.70、25.80、25.60 mm；儀器最小顯示單位 0.1 mm。",skill:"A、B 類組合",prerequisites:"平均、樣本標準差",time:"120–180 秒",image:"assets/uncertainty/measure-5.webp",visual:"uncertainty-repeat",known:["平均值 25.625 mm","uA=s/√n","uB=0.1/√12 mm","uc=√(uA²+uB²)"],models:[option("combine","uc=√(uA²+uB²)"),option("add","uc=uA+uB"),option("onlyB","uc=uB")],correctModel:"combine",inputs:[input("mean","報告平均值","mm",25.63,.015),input("uncertainty","組合標準不確定度","mm",.09,.012)],explanation:"uA≈0.085 mm、uB≈0.029 mm，組合後 uc≈0.090 mm；報告為 (25.63±0.09) mm。",hint:"A、B 類都不可漏掉，且最終平均值小數位要與不確定度對齊。"}
        ]
      }
    },
    {
      id:"momentum",number:"06",eyebrow:"MOMENTUM & COLLISIONS",name:"動量神殿",short:"碰撞與衝量",description:"從碰撞時間、反衝與安全設計建立動量直覺，再以守恆律修復古代石車。",heroImage:"assets/momentum/momentum-temple.png",color:"#ff806b",
      tracks:{
        foundation:[
          {code:"M-F1",title:"衝量之門",summary:"同樣的力作用越久，動量改變越大。",mission:"延長守門槌接觸石車的時間，先預測石車運動改變。",skill:"力與作用時間",prerequisites:"比較、因果",time:"30–60 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-impulse",known:["平均力大小固定","只改變作用時間","石車初始狀態相同"],control:control("作用時間",1,3,1,3,.5,"級"),prediction:prediction("平均力相同，作用時間增加時，石車的動量改變如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("最直接的關係是什麼？","impulse",[["impulse","衝量等於平均力乘作用時間"],["mass","石車質量自動增加"],["gravity","重力消失"]]),explanation:"衝量 J=FΔt 會造成動量改變；同樣的平均力作用越久，動量改變越大。",hint:"把『推多大力』與『推多久』一起看。"},
          {code:"M-F2",title:"反衝石舟",summary:"封閉系統的總動量保持不變。",mission:"巨人從靜止石舟向右丟出石塊，判斷石舟的反應。",skill:"動量守恆質性判斷",prerequisites:"方向",time:"30–60 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-recoil",known:["人、石塊與舟原本都靜止","水平方向外力可忽略","石塊向右飛出"],control:control("拋出速度",1,3,1,3,.5,"級"),prediction:prediction("石塊向右飛出後，石舟會如何？","left",[["left","向左反衝"],["right","跟著向右"],["still","保持不動"]]),reason:reason("為什麼？","total",[["total","總動量仍須維持原本的零"],["wind","石塊製造向左的風"],["weight","石舟突然變輕"]]),explanation:"系統原總動量為零；石塊獲得向右動量時，人舟必須取得向左動量。",hint:"先寫下事件前整個系統的總動量方向。"},
          {code:"M-F3",title:"緩衝結界",summary:"同樣動量變化下，延長碰撞時間可降低平均力。",mission:"替墜落石像選擇厚軟墊或薄石板，避免瞬間破裂。",skill:"安全設計與衝量",prerequisites:"衝量概念",time:"45–75 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-cushion",known:["石像落下速度相同","最後都停止","動量改變相同"],control:control("緩衝時間",1,4,1,4,.5,"級"),prediction:prediction("使用厚軟墊延長停止時間，平均撞擊力如何？","decrease",[["decrease","減少"],["same","不變"],["increase","增加"]]),reason:reason("哪個解釋正確？","same-impulse",[["same-impulse","相同衝量分散在較長時間"],["momentum-zero","動量變化變成零"],["gravity","重力方向改變"]]),explanation:"在相同動量改變下，延長碰撞時間可降低平均力，這也是安全氣囊與護墊的核心。",hint:"J=F平均Δt；J 固定時，F 與 Δt 如何互補？"},
          {code:"M-F4",title:"黏合碰撞",summary:"黏在一起時動量可守恆，但動能通常不守恆。",mission:"兩台石車碰撞後扣在一起，判斷哪些量仍受守恆律約束。",skill:"區分動量與動能",prerequisites:"碰撞現象",time:"45–90 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-stick",known:["水平方向外力可忽略","兩車碰後黏在一起","碰撞伴隨聲音與形變"],control:control("黏合程度",1,3,1,3,1,"級"),prediction:prediction("此碰撞中，哪個判斷最合理？","p-only",[["p-only","總動量守恆，動能通常減少"],["both","動量與動能一定都守恆"],["neither","兩者一定都不守恆"]]),reason:reason("動能減少的能量去了哪裡？","other",[["other","轉為聲音、熱與形變等能量"],["gone","完全消失"],["mass","只變成質量"]]),explanation:"孤立碰撞的總動量守恆；黏合屬完全非彈性碰撞，部分動能轉為內能、聲音與形變。",hint:"『能量守恆』不等於『動能一定守恆』。"}
        ],
        advanced:[
          {code:"M-A1",title:"神槌衝量",summary:"由平均力與作用時間求動量改變。",mission:"神槌以 120 N 的平均力推石車 0.25 s。",skill:"J=FΔt",prerequisites:"乘法、單位",time:"60–100 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-calc-impulse",known:["F平均=120 N","Δt=0.25 s","力方向固定"],models:[option("impulse","J=FΔt"),option("divide","J=F/Δt"),option("energy","J=½FΔt²")],correctModel:"impulse",inputs:[input("impulse","衝量","N·s",30,.2)],explanation:"J=120×0.25=30 N·s，亦即動量改變 30 kg·m/s。",hint:"N·s 與 kg·m/s 是等價單位。"},
          {code:"M-A2",title:"投石反衝",summary:"以總動量守恆求人的反衝速度。",mission:"60 kg 的守衛在靜止舟上向右丟出 3 kg 石塊，石塊速率 8 m/s。",skill:"一維動量守恆",prerequisites:"正負方向、代數",time:"75–130 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-calc-recoil",known:["初總動量為 0","守衛與舟等效質量 60 kg","石塊質量 3 kg、向右 8 m/s"],models:[option("conserve","60v+3×8=0"),option("same","v=8"),option("energy","½60v²=3×8")],correctModel:"conserve",inputs:[input("speed","向左反衝速率","m/s",.4,.02)],explanation:"60v+24=0，v=−0.40 m/s；題目問速率，所以填 0.40。",hint:"先選向右為正，反衝答案自然會出現負號。"},
          {code:"M-A3",title:"合體石車",summary:"求完全非彈性碰撞後的共同速度。",mission:"2 kg 石車以 6 m/s 撞上靜止的 1 kg 石車，碰後黏合。",skill:"完全非彈性碰撞",prerequisites:"動量守恆",time:"75–140 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-calc-stick",known:["m₁=2 kg，v₁=6 m/s","m₂=1 kg，v₂=0","碰後共同速度 v"],models:[option("stick","2×6+1×0=(2+1)v"),option("average","v=(6+0)/2"),option("energy","½2×6²=½3v²")],correctModel:"stick",inputs:[input("speed","共同速度","m/s",4,.05)],explanation:"初動量 12 kg·m/s，總質量 3 kg，所以共同速度為 4 m/s。",hint:"黏在一起後，末態質量要相加。"},
          {code:"M-A4",title:"耗散封印",summary:"比較碰撞前後動能並求損失。",mission:"承接上一關：2 kg 石車以 6 m/s 撞上靜止 1 kg 石車，碰後共同速度 4 m/s。",skill:"碰撞能量分析",prerequisites:"動能、動量守恆",time:"90–160 秒",image:"assets/momentum/momentum-temple.png",visual:"momentum-calc-loss",known:["碰前動能 36 J","碰後總質量 3 kg","共同速度 4 m/s"],models:[option("loss","損失=K前−K後"),option("gain","損失=K後−K前"),option("momentum","損失=p前−p後")],correctModel:"loss",inputs:[input("energy","動能損失","J",12,.1)],explanation:"碰後動能為 ½×3×4²=24 J，碰前為 ½×2×6²=36 J，因此 12 J 轉為內能、聲音與形變。",hint:"先分別計算碰撞前後的總動能，再取差值。"}
        ]
      }
    },
    {
      id:"energy",number:"07",eyebrow:"WORK & ENERGY",name:"能量神殿",short:"功與能量",description:"從功、位能與功率的質性關係出發，再用守恆律穿越熔爐與升降機關。",heroImage:"assets/energy/energy-temple.png",color:"#ffbf5c",
      tracks:{
        foundation:[
          {code:"E-F1",title:"功的方向",summary:"力與位移同向做正功，反向做負功。",mission:"拖動石門時改變施力方向，判斷能量傳遞的正負。",skill:"功的正負",prerequisites:"方向判斷",time:"30–60 秒",image:"assets/energy/energy-temple.png",visual:"energy-work",known:["石門向右移動","施力大小不變","只改變力的方向"],control:control("力與位移夾角",0,180,0,180,30,"°"),prediction:prediction("力由同向轉為反向時，力對石門所做的功如何？","negative",[["negative","由正變負"],["positive","永遠為正"],["zero","永遠為零"]]),reason:reason("判斷依據是什麼？","dot",[["dot","看力在位移方向上的分量"],["time","只看花多少時間"],["mass","只看物體質量"]]),explanation:"功 W=Fd cosθ；同向為正、垂直為零、反向為負。",hint:"比較 θ=0°、90°、180° 時 cosθ 的正負。"},
          {code:"E-F2",title:"高度封印",summary:"同一物體升得越高，重力位能增加越多。",mission:"把同一顆石球送上不同高度的祭壇。",skill:"重力位能質性關係",prerequisites:"比例",time:"30–60 秒",image:"assets/energy/energy-temple.png",visual:"energy-height",known:["石球質量固定","重力場近似固定","只改變高度"],control:control("祭壇高度",1,4,1,4,.5,"級"),prediction:prediction("高度增加時，石球的重力位能如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("最合適的關係是什麼？","mgh",[["mgh","ΔUg 與 mgh 成正比"],["speed","只由速度決定"],["color","由石球顏色決定"]]),explanation:"在近地面，重力位能變化 ΔUg=mgh；質量與 g 固定時，高度越高，位能越多。",hint:"這一關沒有改變石球質量。"},
          {code:"E-F3",title:"摩擦熔爐",summary:"摩擦使機械能轉為內能，但總能量仍守恆。",mission:"石車滑過粗糙地面後變慢，追蹤消失的機械能。",skill:"能量轉換",prerequisites:"動能概念",time:"45–75 秒",image:"assets/energy/energy-temple.png",visual:"energy-friction",known:["地面變粗糙","石車速度下降","石車與地面溫度略升"],control:control("粗糙程度",1,4,1,4,.5,"級"),prediction:prediction("粗糙程度增加時，石車的機械能損失如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("能量主要轉到哪裡？","thermal",[["thermal","石車與地面的內能"],["gone","能量完全消失"],["mass","全部變成質量"]]),explanation:"摩擦會把有組織的機械能轉為較分散的內能；總能量並未消失。",hint:"溫度上升是重要的能量證據。"},
          {code:"E-F4",title:"功率競技",summary:"完成同樣工作，所需時間越短，平均功率越大。",mission:"兩座升降台把相同石塊升到同一高度，只改變完成時間。",skill:"功率質性關係",prerequisites:"比率",time:"45–75 秒",image:"assets/energy/energy-temple.png",visual:"energy-power",known:["兩台做功相同","甲台用時較短","忽略能量損失"],control:control("完成時間",2,8,2,8,1,"s"),prediction:prediction("做功相同，完成時間縮短時平均功率如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("依據哪個定義？","work-time",[["work-time","功率等於功除以時間"],["force-only","功率只等於力"],["mass-time","功率等於質量乘時間"]]),explanation:"平均功率 P=W/Δt；做相同的功，花越少時間代表功率越大。",hint:"功率描述能量轉換的快慢。"}
        ],
        advanced:[
          {code:"E-A1",title:"斜拉石門",summary:"計算斜向力所做的功。",mission:"以 50 N 拉力使石門水平移動 3.0 m，力與位移夾角 60°。",skill:"W=Fd cosθ",prerequisites:"三角函數",time:"60–120 秒",image:"assets/energy/energy-temple.png",visual:"energy-calc-work",known:["F=50 N","d=3.0 m","θ=60°"],models:[option("dot","W=Fd cosθ"),option("sine","W=Fd sinθ"),option("power","W=F/d")],correctModel:"dot",inputs:[input("work","拉力做功","J",75,.5)],explanation:"W=50×3×cos60°=75 J。",hint:"只有沿位移方向的力分量做功。"},
          {code:"E-A2",title:"升高石印",summary:"求提升物體增加的重力位能。",mission:"2.0 kg 石印被緩慢升高 5.0 m，取 g=9.8 m/s²。",skill:"ΔUg=mgh",prerequisites:"乘法、單位",time:"60–100 秒",image:"assets/energy/energy-temple.png",visual:"energy-calc-height",known:["m=2.0 kg","h=5.0 m","g=9.8 m/s²"],models:[option("mgh","ΔUg=mgh"),option("kinetic","ΔUg=½mv²"),option("divide","ΔUg=mg/h")],correctModel:"mgh",inputs:[input("energy","位能增加","J",98,.5)],explanation:"ΔUg=2.0×9.8×5.0=98 J。",hint:"緩慢提升表示動能變化可忽略。"},
          {code:"E-A3",title:"落差之速",summary:"以機械能守恆求落下速度。",mission:"石球由靜止從 5.0 m 高處無摩擦滑下，取 g=9.8 m/s²。",skill:"機械能守恆",prerequisites:"平方根",time:"75–140 秒",image:"assets/energy/energy-temple.png",visual:"energy-calc-speed",known:["初速 0","高度差 5.0 m","忽略摩擦"],models:[option("conserve","mgh=½mv²"),option("linear","v=gh"),option("momentum","mgh=mv")],correctModel:"conserve",inputs:[input("speed","底端速率","m/s",9.9,.1)],explanation:"v=√(2gh)=√98≈9.9 m/s；質量在等式中消去。",hint:"比較頂端的重力位能與底端動能。"},
          {code:"E-A4",title:"升降功率",summary:"由位能變化與時間求平均功率。",mission:"升降台在 4.0 s 內把 30 kg 石像升高 2.0 m，取 g=9.8 m/s²。",skill:"P=W/t",prerequisites:"重力位能",time:"75–130 秒",image:"assets/energy/energy-temple.png",visual:"energy-calc-power",known:["m=30 kg","h=2.0 m","t=4.0 s","忽略損失"],models:[option("power","P=mgh/t"),option("energy","P=mgh"),option("inverse","P=t/mgh")],correctModel:"power",inputs:[input("power","平均功率","W",147,1)],explanation:"P=30×9.8×2/4=147 W。",hint:"先求提升石像所需做功，再除以時間。"}
        ]
      }
    },
    {
      id:"electric",number:"08",eyebrow:"ELECTRIC FIELDS & CIRCUITS",name:"雷霆神殿",short:"電場與電路",description:"先辨認電荷、電場與電路的質性規律，再以庫侖定律與歐姆定律啟動雷霆核心。",heroImage:"assets/electric/electric-temple.png",color:"#84a7ff",
      tracks:{
        foundation:[
          {code:"Q-F1",title:"電荷雙像",summary:"同號相斥、異號相吸。",mission:"轉動電荷石柱，預測兩顆帶電球的移動方向。",skill:"電荷交互作用",prerequisites:"方向",time:"30–60 秒",image:"assets/electric/electric-temple.png",visual:"electric-charge",known:["兩球距離固定","只改變其中一球電性","忽略其他作用"],control:control("右球電性",-1,1,-1,1,2,"號"),prediction:prediction("兩球都帶正電時會如何？","repel",[["repel","互相排斥"],["attract","互相吸引"],["none","沒有作用"]]),reason:reason("判斷依據是什麼？","same",[["same","同號電荷互斥"],["mass","同質量互斥"],["color","同顏色互斥"]]),explanation:"靜電力遵循同號相斥、異號相吸；力在兩電荷連線方向上。",hint:"先辨認正負號，不要用球的大小判斷。"},
          {code:"Q-F2",title:"場線羅盤",summary:"電場方向定義為正試驗電荷受力方向。",mission:"把小正試驗電荷放到正電石柱旁，判斷指針方向。",skill:"電場方向",prerequisites:"正電荷受力",time:"30–60 秒",image:"assets/electric/electric-temple.png",visual:"electric-field",known:["中央為正電荷","試驗電荷為微小正電","不改變原電場"],control:control("觀測距離",1,4,1,4,.5,"格"),prediction:prediction("正電荷周圍的電場線指向何處？","out",[["out","由正電荷向外"],["in","朝正電荷向內"],["circle","繞成圓圈"]]),reason:reason("電場方向如何定義？","positive-test",[["positive-test","正試驗電荷受力方向"],["electron","電子速度方向"],["magnet","指南針方向"]]),explanation:"電場方向以正試驗電荷所受電力方向定義，因此正點電荷的場線向外。",hint:"若放一顆很小的正電荷，它會被推向哪裡？"},
          {code:"Q-F3",title:"串聯回廊",summary:"單一路徑的串聯電路中，各處電流相同。",mission:"兩盞神燈串聯在同一條回路，判斷通過兩燈的電流。",skill:"串聯電流",prerequisites:"封閉電路",time:"45–75 秒",image:"assets/electric/electric-temple.png",visual:"electric-series",known:["電路只有一條路徑","電荷不在燈泡中持續累積","電路達穩定狀態"],control:control("燈泡數",1,2,1,2,1,"顆"),prediction:prediction("串聯兩燈時，通過兩燈的電流如何比較？","same",[["same","相同"],["first","第一顆較大"],["second","第二顆較大"]]),reason:reason("為什麼？","one-path",[["one-path","同一時間通過各截面的電荷量相同"],["used","電流被第一顆用掉"],["voltage","兩燈電壓一定相同"]]),explanation:"串聯只有一條電荷流動路徑，穩定時各處電流相同；被轉換的是電能，不是電流被用完。",hint:"想像同一條水管各截面每秒通過多少水。"},
          {code:"Q-F4",title:"並聯分流",summary:"並聯支路兩端電壓相同，總電流分流。",mission:"開啟第二條神燈支路，觀察電池端的總電流。",skill:"並聯電路質性判斷",prerequisites:"電壓與電流",time:"45–90 秒",image:"assets/electric/electric-temple.png",visual:"electric-parallel",known:["理想電池電壓固定","新增相同電阻支路","兩支路並聯"],control:control("並聯支路",1,3,1,3,1,"條"),prediction:prediction("增加並聯支路時，電池提供的總電流如何？","increase",[["increase","增加"],["same","不變"],["zero","變成零"]]),reason:reason("等效電阻如何變化？","decrease",[["decrease","並聯路徑增加使等效電阻下降"],["increase","支路越多等效電阻越大"],["none","電阻與路徑無關"]]),explanation:"理想電壓源下，增加並聯支路會降低等效電阻，因此總電流增加；各支路兩端電壓相同。",hint:"新增一條路不是把原路堵住，而是增加電荷可走的路徑。"}
        ],
        advanced:[
          {code:"Q-A1",title:"庫侖封印",summary:"由電量與距離求兩點電荷作用力。",mission:"2.0 μC 與 3.0 μC 同號電荷相距 0.30 m，取 k=9.0×10⁹。",skill:"庫侖定律",prerequisites:"科學記號",time:"75–140 秒",image:"assets/electric/electric-temple.png",visual:"electric-calc-force",known:["q₁=2.0 μC","q₂=3.0 μC","r=0.30 m","同號"],models:[option("coulomb","F=k|q₁q₂|/r²"),option("linear","F=k|q₁q₂|/r"),option("add","F=k(q₁+q₂)/r²")],correctModel:"coulomb",inputs:[input("force","電力大小","N",.6,.02)],explanation:"F=9.0×10⁹×(2×10⁻⁶)(3×10⁻⁶)/0.30²=0.60 N，方向互斥。",hint:"μC 要先換成 10⁻⁶ C，距離要平方。"},
          {code:"Q-A2",title:"電場刻度",summary:"求點電荷在指定位置的電場強度。",mission:"4.0 μC 正電荷外 0.30 m，取 k=9.0×10⁹。",skill:"E=kQ/r²",prerequisites:"庫侖定律",time:"75–130 秒",image:"assets/electric/electric-temple.png",visual:"electric-calc-field",known:["Q=4.0 μC","r=0.30 m","場源為正電荷"],models:[option("field","E=kQ/r²"),option("force","E=kQ²/r²"),option("potential","E=kQ/r")],correctModel:"field",inputs:[input("field","電場強度","N/C",400000,3000)],explanation:"E=9.0×10⁹×4.0×10⁻⁶/0.30²=4.0×10⁵ N/C，方向向外。",hint:"電場是每單位正電荷所受的力，不必再乘試驗電荷。"},
          {code:"Q-A3",title:"串聯電流",summary:"由總電阻與電壓求電流。",mission:"4 Ω 與 6 Ω 電阻串聯接上 12 V 理想電池。",skill:"歐姆定律與串聯",prerequisites:"R串=R₁+R₂",time:"60–120 秒",image:"assets/electric/electric-temple.png",visual:"electric-calc-series",known:["R₁=4 Ω","R₂=6 Ω","V=12 V"],models:[option("series","I=V/(R₁+R₂)"),option("parallel","I=V(1/R₁+1/R₂)"),option("multiply","I=V(R₁+R₂)")],correctModel:"series",inputs:[input("current","電流","A",1.2,.02)],explanation:"總電阻 10 Ω，I=12/10=1.2 A。",hint:"串聯電阻先直接相加。"},
          {code:"Q-A4",title:"並聯核心",summary:"求並聯電阻與電源總電流。",mission:"6 Ω 與 3 Ω 電阻並聯接上 12 V 理想電池。",skill:"並聯等效電阻",prerequisites:"倒數、歐姆定律",time:"75–140 秒",image:"assets/electric/electric-temple.png",visual:"electric-calc-parallel",known:["R₁=6 Ω","R₂=3 Ω","V=12 V"],models:[option("parallel","1/Req=1/R₁+1/R₂"),option("series","Req=R₁+R₂"),option("average","Req=(R₁+R₂)/2")],correctModel:"parallel",inputs:[input("resistance","等效電阻","Ω",2,.03),input("current","總電流","A",6,.05)],explanation:"1/Req=1/6+1/3=1/2，所以 Req=2 Ω；總電流 I=12/2=6 A。",hint:"並聯等效電阻一定小於最小的支路電阻。"}
        ]
      }
    },
    {
      id:"magnetic",number:"09",eyebrow:"MAGNETISM & INDUCTION",name:"磁序神殿",short:"磁場與感應",description:"從磁極、洛倫茲力與磁通量變化建立方向感，再計算帶電粒子與感應電動勢。",heroImage:"assets/magnetic/magnetic-temple.png",color:"#69dbcb",
      tracks:{
        foundation:[
          {code:"B-F1",title:"磁極之門",summary:"同名磁極相斥，異名磁極相吸。",mission:"轉動兩根磁柱，預測神門是閉合或彈開。",skill:"磁極交互作用",prerequisites:"方向",time:"30–60 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-poles",known:["兩磁柱距離固定","只改變右柱朝向","忽略其他力"],control:control("右柱朝向",1,2,1,2,1,"式"),prediction:prediction("兩個 N 極相對時會如何？","repel",[["repel","互相排斥"],["attract","互相吸引"],["none","沒有作用"]]),reason:reason("正確規則是什麼？","pole-rule",[["pole-rule","同名相斥、異名相吸"],["charge-rule","N 極必定帶正電"],["mass-rule","磁力只看質量"]]),explanation:"磁極遵循同名相斥、異名相吸；但 N、S 極不是可單獨分離的正負電荷。",hint:"不要把磁極與電荷直接畫上等號。"},
          {code:"B-F2",title:"洛倫茲羅盤",summary:"磁力同時垂直於速度與磁場。",mission:"讓正電粒子水平進入垂直紙面的磁場，判斷路徑。",skill:"磁力方向質性判斷",prerequisites:"三維方向",time:"45–75 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-lorentz",known:["粒子帶正電","速度向右","磁場垂直紙面向內"],control:control("磁場強度",1,4,1,4,.5,"級"),prediction:prediction("正電粒子剛進入時受力方向為何？","up",[["up","向上"],["right","向右"],["into","向紙面內"]]),reason:reason("磁力與速度的關係是什麼？","perpendicular",[["perpendicular","磁力垂直速度，因此改方向不直接改速率"],["parallel","磁力永遠沿速度"],["zero","運動電荷永遠不受磁力"]]),explanation:"正電荷的磁力方向由 q v×B 決定；此例向上，且磁力垂直速度。",hint:"先用右手判斷 v×B；若是負電荷再反向。"},
          {code:"B-F3",title:"載流石橋",summary:"電流方向改變時，導線所受磁力方向反轉。",mission:"讓載流導線穿過固定磁場，切換電流方向觀察石橋偏轉。",skill:"載流導線磁力",prerequisites:"方向判斷",time:"45–75 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-wire",known:["磁場方向固定","導線與磁場垂直","只反轉電流"],control:control("電流方向",-1,1,-1,1,2,"向"),prediction:prediction("電流反向後，導線受磁力方向如何？","reverse",[["reverse","反轉"],["same","不變"],["zero","必定變零"]]),reason:reason("為什麼？","cross",[["cross","F=IL×B，L 反向使叉積反向"],["heat","導線溫度下降"],["charge","電流反向使導線不帶電"]]),explanation:"載流導線磁力由 I L×B 決定；磁場不變、電流反向時，磁力方向也反轉。",hint:"把電流方向當作 L 向量方向。"},
          {code:"B-F4",title:"感應封印",summary:"磁通量變化越快，感應電動勢越大。",mission:"把磁石以不同速度推入線圈，預測神燈亮度。",skill:"法拉第定律質性判斷",prerequisites:"變化率",time:"45–90 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-induction",known:["磁石、線圈相同","進入的總磁通量改變相同","只改變完成時間"],control:control("磁石移動速度",1,4,1,4,.5,"級"),prediction:prediction("磁石更快推入線圈時，瞬間感應電動勢如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("關鍵是什麼？","rate",[["rate","單位時間磁通量改變更大"],["flux-only","只看最後磁通量"],["magnet-mass","磁石質量變大"]]),explanation:"法拉第定律看的是磁通量變化率；同樣的改變在更短時間完成，感應電動勢較大。",hint:"比較 ΔΦ/Δt，不只比較 ΔΦ。"}
        ],
        advanced:[
          {code:"B-A1",title:"粒子受力",summary:"計算垂直入射帶電粒子的磁力。",mission:"2.0 μC 正電粒子以 3.0×10⁴ m/s 垂直進入 0.50 T 磁場。",skill:"F=qvB sinθ",prerequisites:"科學記號",time:"75–130 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-calc-force",known:["q=2.0 μC","v=3.0×10⁴ m/s","B=0.50 T","θ=90°"],models:[option("lorentz","F=qvB sinθ"),option("electric","F=qB/v"),option("square","F=qv²B")],correctModel:"lorentz",inputs:[input("force","磁力大小","N",.03,.002)],explanation:"F=2.0×10⁻⁶×3.0×10⁴×0.50=0.030 N。",hint:"垂直入射時 sin90°=1。"},
          {code:"B-A2",title:"圓軌半徑",summary:"由向心力等於磁力求圓周半徑。",mission:"質量 0.004 kg、電量 0.002 C 的帶電珠以 3.0 m/s 垂直進入 2.0 T 磁場。",skill:"r=mv/qB",prerequisites:"圓周運動",time:"90–160 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-calc-radius",known:["m=0.004 kg","q=0.002 C","v=3.0 m/s","B=2.0 T"],models:[option("radius","qvB=mv²/r"),option("energy","qB=½mv²"),option("period","r=qB/mv")],correctModel:"radius",inputs:[input("radius","軌道半徑","m",3,.05)],explanation:"r=mv/qB=(0.004×3)/(0.002×2)=3.0 m。",hint:"磁力提供向心力，先消去等式兩邊共同的 v。"},
          {code:"B-A3",title:"石橋磁力",summary:"求垂直磁場中載流導線受力。",mission:"0.50 m 導線通 3.0 A 電流，垂直放入 0.40 T 磁場。",skill:"F=BIL",prerequisites:"乘法",time:"60–110 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-calc-wire",known:["B=0.40 T","I=3.0 A","L=0.50 m","θ=90°"],models:[option("wire","F=BIL sinθ"),option("ohm","F=V/R"),option("square","F=BI²L")],correctModel:"wire",inputs:[input("force","磁力大小","N",.6,.02)],explanation:"F=0.40×3.0×0.50=0.60 N。",hint:"導線與磁場垂直，角度因子為 1。"},
          {code:"B-A4",title:"法拉第核心",summary:"由磁通量變化率求平均感應電動勢。",mission:"200 匝線圈的每匝磁通量在 0.50 s 內改變 0.030 Wb。",skill:"|ε|=N|ΔΦ|/Δt",prerequisites:"變化率",time:"75–140 秒",image:"assets/magnetic/magnetic-temple.png",visual:"magnetic-calc-emf",known:["N=200","|ΔΦ|=0.030 Wb","Δt=0.50 s"],models:[option("faraday","|ε|=N|ΔΦ|/Δt"),option("single","|ε|=|ΔΦ|/(NΔt)"),option("product","|ε|=N|ΔΦ|Δt")],correctModel:"faraday",inputs:[input("emf","平均感應電動勢","V",12,.1)],explanation:"|ε|=200×0.030/0.50=12 V；負號只描述楞次定律方向。",hint:"題目問大小，先處理 N 倍磁通鏈結的變化率。"}
        ]
      }
    },
    {
      id:"optics",number:"10",eyebrow:"GEOMETRIC OPTICS",name:"鏡光神殿",short:"折射與成像",description:"從反射、折射與透鏡光線建立圖像直覺，再用司乃耳定律與薄透鏡公式解鎖光門。",heroImage:"assets/optics/optics-temple.png",color:"#b99cff",
      tracks:{
        foundation:[
          {code:"O-F1",title:"反射之鏡",summary:"入射角等於反射角，角度都由法線量起。",mission:"轉動入射光束，預測反射光的對稱方向。",skill:"反射定律",prerequisites:"角度、法線",time:"30–60 秒",image:"assets/optics/optics-temple.png",visual:"optics-reflection",known:["鏡面平坦","法線垂直鏡面","角度由法線量起"],control:control("入射角",15,60,0,75,5,"°"),prediction:prediction("入射角增加時，反射角如何？","increase",[["increase","等量增加"],["same","保持不變"],["opposite","變成其餘角"]]),reason:reason("正確關係是什麼？","equal",[["equal","入射角等於反射角"],["surface","兩角都由鏡面量起"],["speed","反射角由光速決定"]]),explanation:"反射定律為 θi=θr，且兩角都以法線為基準。",hint:"先畫法線，再量光線與法線的夾角。"},
          {code:"O-F2",title:"折射之泉",summary:"光進入折射率較大介質時向法線偏折。",mission:"讓光從空氣斜射進水晶，預測折射光方向。",skill:"折射質性判斷",prerequisites:"法線",time:"30–60 秒",image:"assets/optics/optics-temple.png",visual:"optics-refraction",known:["光由空氣進入水晶","水晶折射率較大","入射角不為零"],control:control("水晶折射率",1.2,1.8,1.1,2,.1,""),prediction:prediction("進入折射率較大介質時，光線如何偏折？","toward",[["toward","向法線"],["away","離開法線"],["none","一定不偏折"]]),reason:reason("同時哪一項會變小？","speed",[["speed","光在介質中的速率"],["frequency","光的頻率"],["color","光源的顏色一定消失"]]),explanation:"光進入折射率較大、速率較小的介質時向法線偏折；跨界面時頻率保持不變。",hint:"n 越大表示介質中光速越小。"},
          {code:"O-F3",title:"全反射密道",summary:"全反射只能由高折射率射向低折射率且角度夠大。",mission:"調整水晶內光線角度，找出光不再穿出界面的條件。",skill:"全反射條件",prerequisites:"折射方向",time:"45–75 秒",image:"assets/optics/optics-temple.png",visual:"optics-tir",known:["光由水晶射向空氣","水晶折射率較大","逐漸增加入射角"],control:control("入射角",20,60,10,80,5,"°"),prediction:prediction("入射角超過臨界角後會出現什麼？","tir",[["tir","全反射"],["normal","折射光沿法線"],["stop","光能完全消失"]]),reason:reason("必要條件是哪一項？","high-low",[["high-low","由高折射率射向低折射率"],["low-high","只能由低射向高"],["any","任何界面都一定全反射"]]),explanation:"全反射需同時滿足由高 n 射向低 n，以及入射角大於臨界角。",hint:"光纖把光留在核心，就是利用這兩個條件。"},
          {code:"O-F4",title:"透鏡之眼",summary:"凸透鏡可讓平行光會聚到焦點。",mission:"移動光源到很遠處，觀察凸透鏡後的光線。",skill:"凸透鏡基本光線",prerequisites:"平行線",time:"45–75 秒",image:"assets/optics/optics-temple.png",visual:"optics-lens",known:["薄凸透鏡","入射光近似平行主軸","忽略像差"],control:control("光束平行度",1,3,1,3,.5,"級"),prediction:prediction("平行主軸光經凸透鏡後通過何處？","focus",[["focus","像側焦點"],["center","永遠停在透鏡中心"],["parallel","仍完全平行"]]),reason:reason("這條規則可用來做什麼？","ray",[["ray","建立成像光線圖"],["energy","判斷光子能量"],["charge","求電荷量"]]),explanation:"平行主軸的近軸光經凸透鏡後會通過像側焦點，是幾何光學作圖的基本光線。",hint:"焦點不是物體所在位置，而是折射後光線會聚的位置。"}
        ],
        advanced:[
          {code:"O-A1",title:"司乃耳之門",summary:"由折射率與入射角求折射角。",mission:"光由空氣 n₁=1.00 以 30° 入射玻璃 n₂=1.50。",skill:"n₁sinθ₁=n₂sinθ₂",prerequisites:"反三角函數",time:"75–140 秒",image:"assets/optics/optics-temple.png",visual:"optics-calc-snell",known:["n₁=1.00","n₂=1.50","θ₁=30°","角度由法線量起"],models:[option("snell","n₁sinθ₁=n₂sinθ₂"),option("linear","n₁θ₁=n₂θ₂"),option("cos","n₁cosθ₁=n₂cosθ₂")],correctModel:"snell",inputs:[input("angle","折射角","°",19.5,.3)],explanation:"sinθ₂=(1/1.5)sin30°=1/3，所以 θ₂≈19.5°。",hint:"折射角應小於 30°，可先用質性判斷檢核。"},
          {code:"O-A2",title:"臨界角封印",summary:"計算玻璃射向空氣的臨界角。",mission:"玻璃折射率 1.50，外界空氣折射率 1.00。",skill:"sinθc=n₂/n₁",prerequisites:"全反射、反三角函數",time:"75–140 秒",image:"assets/optics/optics-temple.png",visual:"optics-calc-critical",known:["n高=1.50","n低=1.00","臨界時折射角 90°"],models:[option("critical","sinθc=n低/n高"),option("reverse","sinθc=n高/n低"),option("difference","θc=90°(n高−n低)")],correctModel:"critical",inputs:[input("angle","臨界角","°",41.8,.3)],explanation:"θc=sin⁻¹(1/1.5)≈41.8°。",hint:"sinθc 不可能大於 1，可用來排除倒置的比值。"},
          {code:"O-A3",title:"薄透鏡密碼",summary:"由焦距與物距求像距。",mission:"焦距 10 cm 的凸透鏡前方 30 cm 放置物體。",skill:"1/f=1/do+1/di",prerequisites:"分數方程",time:"75–140 秒",image:"assets/optics/optics-temple.png",visual:"optics-calc-lens",known:["f=+10 cm","do=30 cm","薄透鏡近軸近似"],models:[option("lens","1/f=1/do+1/di"),option("sum","di=do+f"),option("product","di=dof")],correctModel:"lens",inputs:[input("distance","像距","cm",15,.2)],explanation:"1/di=1/10−1/30=1/15，所以 di=15 cm，形成實像。",hint:"物距大於焦距，像應在透鏡另一側。"},
          {code:"O-A4",title:"成像倍率",summary:"由像距與物距求像高與方向。",mission:"承接上一關：do=30 cm、di=15 cm，物高 4.0 cm。",skill:"m=hi/ho=−di/do",prerequisites:"符號與比例",time:"60–120 秒",image:"assets/optics/optics-temple.png",visual:"optics-calc-magnify",known:["do=30 cm","di=15 cm","ho=+4.0 cm"],models:[option("magnify","hi/ho=−di/do"),option("positive","hi/ho=di/do"),option("sum","hi=ho+di/do")],correctModel:"magnify",inputs:[input("height","像高（含正負）","cm",-2,.05)],explanation:"hi=4.0×(−15/30)=−2.0 cm；負號表示倒立。",hint:"先算倍率 −di/do，再乘物高。"}
        ]
      }
    },
    {
      id:"thermal",number:"11",eyebrow:"THERMAL PHYSICS",name:"熾熱神殿",short:"熱學與氣體",description:"從熱平衡、熱容量與氣體狀態建立直覺，再以熱量、理想氣體與第一定律穿越熔爐。",heroImage:"assets/thermal/thermal-temple.png",color:"#ff8b61",
      tracks:{
        foundation:[
          {code:"H-F1",title:"熱流之向",summary:"能量自高溫物體傳向低溫物體，直到熱平衡。",mission:"把熱石與冷石接觸，預測兩者溫度變化。",skill:"熱傳方向",prerequisites:"溫度比較",time:"30–60 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-flow",known:["熱石溫度較高","冷石溫度較低","兩者可交換能量"],control:control("接觸時間",0,5,0,5,1,"級"),prediction:prediction("接觸後的淨熱傳方向為何？","hot-cold",[["hot-cold","由熱石到冷石"],["cold-hot","由冷石到熱石"],["none","只要接觸就沒有熱傳"]]),reason:reason("何時停止淨熱傳？","equal-temp",[["equal-temp","兩者達到相同溫度"],["same-mass","兩者質量相同"],["zero-energy","兩者能量都變零"]]),explanation:"溫差驅動淨熱傳；達熱平衡時溫度相同，但兩物體仍具有內能。",hint:"不要把『沒有淨熱傳』誤認為『沒有能量』。"},
          {code:"H-F2",title:"升溫競賽",summary:"吸收同樣熱量時，熱容量較小者溫升較大。",mission:"向兩顆不同材質石球輸入相同能量，預測溫度變化。",skill:"熱容量質性關係",prerequisites:"反比趨勢",time:"30–60 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-capacity",known:["吸收熱量相同","初溫相同","甲的熱容量較小"],control:control("熱容量",1,4,1,4,.5,"級"),prediction:prediction("熱容量較小的甲球，溫度改變如何？","larger",[["larger","較大"],["same","相同"],["smaller","較小"]]),reason:reason("依據哪個關係？","q-over-c",[["q-over-c","ΔT=Q/C"],["mass-only","溫升只由質量決定"],["time-only","溫升只由時間決定"]]),explanation:"熱容量 C 描述物體升高一度所需能量；同樣 Q 下，C 越小，ΔT 越大。",hint:"把熱容量想成物體吸收熱量的『緩衝能力』。"},
          {code:"H-F3",title:"定容氣室",summary:"定容加熱理想氣體時，壓力隨絕對溫度增加。",mission:"封閉剛性氣室並加熱，預測壓力指針。",skill:"氣體狀態質性關係",prerequisites:"溫度、壓力",time:"45–75 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-gas",known:["氣體量固定","容器體積固定","使用絕對溫度"],control:control("絕對溫度",300,600,300,600,50,"K"),prediction:prediction("定容下溫度升高時，壓力如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("微觀上發生什麼？","collisions",[["collisions","分子撞壁更頻繁且動量改變更大"],["molecules","分子數自動減少"],["volume","容器體積必定增加"]]),explanation:"固定 n、V 時，理想氣體 P∝T；升溫使分子平均動能增加，撞壁效應增強。",hint:"攝氏溫度不能直接做倍數比較，要用 K。"},
          {code:"H-F4",title:"壓縮火種",summary:"快速絕熱壓縮會使氣體內能與溫度上升。",mission:"快速壓下密閉氣缸，預測缸內氣體溫度。",skill:"功與內能質性關係",prerequisites:"能量轉換",time:"45–90 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-compress",known:["壓縮很快，熱交換可忽略","外界對氣體做功","氣體量不變"],control:control("壓縮程度",1,4,1,4,.5,"級"),prediction:prediction("快速壓縮時，氣體溫度如何？","increase",[["increase","升高"],["same","不變"],["decrease","降低"]]),reason:reason("能量從哪裡來？","work-in",[["work-in","外界做功增加氣體內能"],["heat-in","一定由外界傳熱"],["mass","氣體質量增加"]]),explanation:"絕熱表示 Q≈0；外界對氣體做功使內能增加，因此溫度升高。",hint:"快速壓縮的關鍵是來不及與外界交換熱。"}
        ],
        advanced:[
          {code:"H-A1",title:"水之熱量",summary:"由質量、比熱與溫差求吸熱量。",mission:"0.50 kg 水升溫 10°C，取 c=4200 J/(kg·°C)。",skill:"Q=mcΔT",prerequisites:"乘法、單位",time:"60–110 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-calc-heat",known:["m=0.50 kg","c=4200 J/(kg·°C)","ΔT=10°C"],models:[option("heat","Q=mcΔT"),option("divide","Q=mΔT/c"),option("power","Q=mc/ΔT")],correctModel:"heat",inputs:[input("heat","吸收熱量","J",21000,100)],explanation:"Q=0.50×4200×10=2.1×10⁴ J。",hint:"溫差用 °C 或 K 數值相同。"},
          {code:"H-A2",title:"混合平衡",summary:"以能量守恆求兩份水的平衡溫度。",mission:"等質量、無熱損的 80°C 與 20°C 水混合。",skill:"熱平衡",prerequisites:"Q放=Q吸",time:"75–130 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-calc-mix",known:["兩份水質量相同","比熱相同","忽略容器與散熱"],models:[option("balance","mc(80−T)=mc(T−20)"),option("add","T=80+20"),option("geometric","T=√(80×20)")],correctModel:"balance",inputs:[input("temperature","平衡溫度","°C",50,.3)],explanation:"相同熱容量下，平衡溫度為兩初溫平均值 50°C。",hint:"熱水降溫放出的能量等於冷水升溫吸收的能量。"},
          {code:"H-A3",title:"氣體石碑",summary:"使用理想氣體方程求壓力。",mission:"1.00 mol 理想氣體在 300 K、體積 0.0249 m³，取 R=8.31。",skill:"PV=nRT",prerequisites:"單位、科學記號",time:"75–140 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-calc-gas",known:["n=1.00 mol","T=300 K","V=0.0249 m³","R=8.31 J/(mol·K)"],models:[option("ideal","P=nRT/V"),option("multiply","P=nRTV"),option("inverse","P=V/nRT")],correctModel:"ideal",inputs:[input("pressure","壓力","kPa",100,.6)],explanation:"P=1×8.31×300/0.0249≈1.00×10⁵ Pa=100 kPa。",hint:"最後要把 Pa 除以 1000 轉為 kPa。"},
          {code:"H-A4",title:"第一定律核心",summary:"由吸熱與氣體對外做功求內能變化。",mission:"氣體吸收 500 J 熱量，同時對外做功 200 J。",skill:"ΔU=Q−Wby",prerequisites:"正負號",time:"60–120 秒",image:"assets/thermal/thermal-temple.png",visual:"thermal-calc-firstlaw",known:["Q=+500 J","氣體對外做功 Wby=+200 J","採 ΔU=Q−Wby 慣例"],models:[option("firstlaw","ΔU=Q−Wby"),option("add","ΔU=Q+Wby"),option("ratio","ΔU=Q/Wby")],correctModel:"firstlaw",inputs:[input("energy","內能增加","J",300,3)],explanation:"ΔU=500−200=300 J；吸收能量中有 200 J 已轉移為對外做功。",hint:"先確認題目明確採用的是『氣體對外做功為正』。"}
        ]
      }
    },
    {
      id:"celestial",number:"12",eyebrow:"GRAVITY & ORBITS",name:"星辰神殿",short:"萬有引力與軌道",description:"從距離、向心加速度與軌道週期建立天體直覺，再以萬有引力和克卜勒定律修復星圖。",heroImage:"assets/celestial/celestial-temple.png",color:"#91a8ff",
      tracks:{
        foundation:[
          {code:"S-F1",title:"距離之律",summary:"距離增加時，萬有引力快速減弱。",mission:"拉開兩顆星石的距離，預測引力刻度。",skill:"反平方質性關係",prerequisites:"倍數",time:"30–60 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-gravity",known:["兩星石質量固定","只改變中心距離","忽略其他天體"],control:control("距離倍數",1,3,1,3,.5,"倍"),prediction:prediction("距離變為 2 倍時，引力變為多少？","quarter",[["quarter","1/4"],["half","1/2"],["double","2 倍"]]),reason:reason("依據哪個關係？","inverse-square",[["inverse-square","F 與 1/r² 成正比"],["inverse","F 與 1/r 成正比"],["direct","F 與 r 成正比"]]),explanation:"萬有引力遵循反平方律；距離加倍，引力變為原來四分之一。",hint:"距離在公式分母中要平方。"},
          {code:"S-F2",title:"圓軌之心",summary:"等速圓周運動仍有指向圓心的加速度。",mission:"觀察繞行星石，判斷速度與加速度方向。",skill:"圓周運動方向",prerequisites:"速度向量",time:"30–60 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-circular",known:["軌道近似圓形","速率固定","引力提供向心力"],control:control("軌道位置",0,3,0,3,1,"象限"),prediction:prediction("衛星在圓軌道上，加速度指向何處？","center",[["center","圓心"],["tangent","沿切線前方"],["outside","背離圓心"]]),reason:reason("即使速率不變，為何仍有加速度？","direction-change",[["direction-change","速度方向持續改變"],["speed-zero","衛星速度為零"],["mass-change","衛星質量持續變化"]]),explanation:"加速度描述速度向量的改變；等速圓周運動雖速率不變，方向持續改變，因此有向心加速度。",hint:"速度是有方向的向量。"},
          {code:"S-F3",title:"外軌節奏",summary:"同一中心天體下，較遠的圓軌道速率較小、週期較長。",mission:"把衛星移到更外層軌道，預測它繞行的節奏。",skill:"軌道半徑與週期",prerequisites:"比較",time:"45–75 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-period",known:["中心天體相同","比較兩條圓軌道","衛星質量不影響理想軌道週期"],control:control("軌道半徑",1,4,1,4,.5,"級"),prediction:prediction("軌道半徑增加時，週期通常如何？","increase",[["increase","變長"],["same","不變"],["decrease","變短"]]),reason:reason("哪個描述同時正確？","slower-longer",[["slower-longer","外軌道速率較小且路徑較長"],["faster","外軌道速率一定更大"],["mass","週期只由衛星質量決定"]]),explanation:"同一中心天體下，外軌道引力較弱、圓軌道速率較小，且路徑更長，因此週期更長。",hint:"不要只比較圓周長，也要比較軌道速率。"},
          {code:"S-F4",title:"質量與重量",summary:"質量描述物質多寡，重量取決於所在地重力場。",mission:"把同一位探險者從地球傳送到月球。",skill:"區分質量與重量",prerequisites:"重力",time:"30–60 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-weight",known:["探險者未失去物質","月球表面重力較小","使用同一台校準好的質量測量方式"],control:control("重力場強度",1,9.8,1,9.8,1.1,"N/kg"),prediction:prediction("到月球後，哪一項正確？","mass-same",[["mass-same","質量不變，重量變小"],["both-small","質量與重量都等比例變小"],["weight-same","重量不變"]]),reason:reason("重量如何計算？","mg",[["mg","W=mg，g 隨地點改變"],["m-over-g","W=m/g"],["m-only","W 只等於質量"]]),explanation:"質量是物體的慣性與物質量特徵；重量是重力 W=mg，因此會隨所在地 g 改變。",hint:"問自己：人到月球後，原子數會突然變少嗎？"}
        ],
        advanced:[
          {code:"S-A1",title:"萬有引力",summary:"計算兩顆星石間的引力。",mission:"兩顆 1000 kg 星石中心相距 10 m，取 G=6.67×10⁻¹¹。",skill:"F=Gm₁m₂/r²",prerequisites:"科學記號",time:"75–140 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-calc-gravity",known:["m₁=m₂=1000 kg","r=10 m","G=6.67×10⁻¹¹ N·m²/kg²"],models:[option("gravity","F=Gm₁m₂/r²"),option("linear","F=Gm₁m₂/r"),option("add","F=G(m₁+m₂)/r²")],correctModel:"gravity",inputs:[input("force","引力大小","N",0.000000667,.00000002)],explanation:"F=6.67×10⁻¹¹×10⁶/10²=6.67×10⁻⁷ N。",hint:"兩個 1000 相乘是 10⁶，距離平方是 10²。"},
          {code:"S-A2",title:"近地軌速",summary:"由萬有引力提供向心力求圓軌道速率。",mission:"取地球 GM=3.986×10¹⁴ m³/s²，軌道半徑 r=6.37×10⁶ m。",skill:"v=√(GM/r)",prerequisites:"向心力、平方根",time:"90–160 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-calc-speed",known:["GM=3.986×10¹⁴ m³/s²","r=6.37×10⁶ m","圓軌道"],models:[option("orbit","v=√(GM/r)"),option("escape","v=√(2GM/r)"),option("linear","v=GM/r")],correctModel:"orbit",inputs:[input("speed","軌道速率","km/s",7.91,.08)],explanation:"v=√(3.986×10¹⁴/6.37×10⁶)≈7.91×10³ m/s=7.91 km/s。",hint:"這是圓軌道速率，不是逃逸速率。"},
          {code:"S-A3",title:"軌道週期",summary:"由圓周長與速率求繞行週期。",mission:"衛星軌道半徑 7.0×10⁶ m，速率 7.5×10³ m/s。",skill:"T=2πr/v",prerequisites:"圓周長",time:"75–140 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-calc-period",known:["r=7.0×10⁶ m","v=7.5×10³ m/s","圓軌道"],models:[option("period","T=2πr/v"),option("frequency","T=v/2πr"),option("area","T=πr²/v")],correctModel:"period",inputs:[input("period","週期","s",5864,35)],explanation:"T=2π(7.0×10⁶)/(7.5×10³)≈5864 s，約 97.7 分鐘。",hint:"一圈路程是 2πr，再除以每秒前進距離。"},
          {code:"S-A4",title:"克卜勒比例",summary:"以第三定律比較兩條軌道週期。",mission:"兩衛星繞同一中心天體，外衛星軌道半徑是內衛星 4 倍。",skill:"T²∝r³",prerequisites:"指數律",time:"75–140 秒",image:"assets/celestial/celestial-temple.png",visual:"celestial-calc-kepler",known:["中心天體相同","r₂/r₁=4","T²/r³ 為常數"],models:[option("kepler","T₂/T₁=(r₂/r₁)^(3/2)"),option("linear","T₂/T₁=r₂/r₁"),option("inverse","T₂/T₁=(r₁/r₂)²")],correctModel:"kepler",inputs:[input("ratio","週期比 T₂/T₁","倍",8,.1)],explanation:"T₂/T₁=4^(3/2)=√(4³)=8。",hint:"先立方再開平方，或把 4 寫成 2²。"}
        ]
      }
    }
  ];

  const lore = {
    titans:{act:"第一幕｜甦醒",region:"巨像荒原",guardian:"銅臂守望者・塔洛斯",relic:"力矩刻印",crisis:"失序讓所有關節的支點與施力線錯位，巨像正被自己的力量撕裂。",oath:"真正的力量，不只取決於力有多大，也取決於它從哪裡、往哪裡作用。"},
    chrono:{act:"第一幕｜甦醒",region:"斷時長廊",guardian:"軌跡記錄官・刻羅",relic:"時序刻印",crisis:"事件先後與運動軌跡互相錯置，列車被困在永不相遇的時間迴圈。",oath:"不必追逐時間；讀懂軌跡，時間會自己說明發生了什麼。"},
    photo:{act:"第一幕｜甦醒",region:"古光銀河",guardian:"光門祭司・赫利亞",relic:"光子刻印",crisis:"古光封印混淆了亮度與頻率，使再強的光也無法找到正確門檻。",oath:"世界並非只由連續光流構成；有時，能量是一份一份抵達。"},
    ripple:{act:"第一幕｜甦醒",region:"沉眠水庭",guardian:"雙泉吟遊者・涅瑞伊",relic:"波紋刻印",crisis:"兩座聖泉失去共同節奏，節線與腹線交織成封住水門的迷宮。",oath:"每一道波都保有自己的聲音，而世界在它們重疊時寫出新的圖樣。"},
    uncertainty:{act:"第二幕｜裂隙",region:"真理量室",guardian:"無刻度者・梅特拉",relic:"證據刻印",crisis:"失序把數字偽裝成絕對真理；量測者忘了每個答案都帶著解析度與散布。",oath:"誠實的數字承認自己的界線；不確定不是無知，而是證據的形狀。"},
    momentum:{act:"第二幕｜裂隙",region:"碰撞聖所",guardian:"赤輪裁決者・伊姆佩圖斯",relic:"動量刻印",crisis:"石車戰陣失去碰撞法則，衝擊沿城市無限放大，連守護者也無法停下。",oath:"力量也許只出現一瞬，但它留下的動量會被整個系統記住。"},
    energy:{act:"第二幕｜裂隙",region:"守恆熔爐",guardian:"熔爐司秤・厄爾貢",relic:"能量刻印",crisis:"機械能似乎在摩擦中消失，熔爐因無人追蹤能量去向而逐漸熄滅。",oath:"能量不會憑空消失；它只是換了比較難被看見的形式。"},
    electric:{act:"第二幕｜裂隙",region:"雷霆迴廊",guardian:"雙極執政官・伏爾塔",relic:"電場刻印",crisis:"電荷與電流失去路徑，雷霆在神殿內盲目分流，核心即將過載。",oath:"看不見的場為每個位置留下方向；閉合的路徑讓能量得以流動。"},
    magnetic:{act:"第三幕｜統一",region:"磁序迷宮",guardian:"北冕羅盤・洛倫茲",relic:"磁序刻印",crisis:"電與磁被失序硬生生拆開，帶電粒子在迷宮裡失去彎曲與感應的方向。",oath:"磁力不推你更快，它改變你面向的道路；變動的磁通則喚醒電。"},
    optics:{act:"第三幕｜統一",region:"折光鏡城",guardian:"稜鏡鑄師・斯涅爾",relic:"鏡光刻印",crisis:"鏡城的法線全部傾倒，反射、折射與成像再也找不到共同的幾何秩序。",oath:"光線選擇的不是神祕捷徑，而是可以被幾何與比例讀懂的道路。"},
    thermal:{act:"第三幕｜統一",region:"熾熱氣室",guardian:"焰心記錄官・卡諾",relic:"熱力刻印",crisis:"熱流與功的帳目被抹除，氣室一面結霜、一面失控膨脹。",oath:"熱與功是跨越系統邊界的兩種能量傳遞；內能記錄了它們留下的結果。"},
    celestial:{act:"終幕｜天穹",region:"十二環天文台",guardian:"星圖守望者・克卜勒",relic:"軌道刻印",crisis:"十二座神殿的法則失去共鳴，天穹軌道逐圈偏離，失序核心即將墜落世界。",oath:"落下與繞行原來屬於同一條法則；當十二刻印共鳴，天空也能被理解。"}
  };
  temples.forEach(temple => Object.assign(temple, lore[temple.id]));

  const totals = temples.reduce((acc, temple) => {
    acc.foundation += temple.tracks.foundation.length;
    acc.advanced += temple.tracks.advanced.length;
    return acc;
  }, { foundation: 0, advanced: 0 });

  return {
    version: "4.1.0",
    world: {
      title: "法則神殿：失序紀元",
      role: "你是最後一位法則修復者。",
      premise: "世界曾由十二座神殿共同維持：力、時間、光、波、量測、碰撞、能量、電場、磁場、折射、熱與星辰彼此共鳴。如今「失序」竄入法則網，使現象仍在發生，原因卻彼此錯接。",
      mission: "進入每座神殿，先立下預測，再讓機關顯示證據；取得初階的觀測印與進階的演算印，喚醒十二位守護者，重建天穹中央的法則核心。",
      finale: "集齊十二組雙印後，星辰神殿將開啟最終共鳴。真正的勝利不是背出公式，而是能用模型解釋世界，也能在證據不支持時修正自己。"
    },
    tracks: {
      foundation: { label: "初階殿", grade: "高一基礎／必修概念適合", task: "觀念・質性判斷", ability: "讀圖、比較、簡單比例", duration: "30–90 秒" },
      advanced: { label: "進階殿", grade: "高二／高三加深加廣適合", task: "模型・計算挑戰", ability: "代數、向量、三角函數或有效數字", duration: "60–180 秒" }
    },
    totals,
    temples
  };
});
