(function (root, factory) {
  const value = factory();
  if (typeof module === "object" && module.exports) module.exports = value;
  root.TempleData = value;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const option = (value, label) => ({ value, label });
  const prediction = (question, correct, labels) => ({ question, correct, options: labels.map(([value, label]) => option(value, label)) });
  const reason = (question, correct, labels) => ({ question, correct, options: labels.map(([value, label]) => option(value, label)) });
  const control = (label, base, target, min, max, step, unit) => ({ label, base, target, min, max, step, unit });
  const input = (id, label, unit, answer, tolerance) => ({ id, label, unit, answer, tolerance });

  const temples = [
    {
      id: "titans", number: "01", eyebrow: "BIOMECHANICS", name: "巨人神殿", short: "生物力學",
      description: "從支點與姿勢建立人體力矩直覺，再以靜力平衡解開巨人的肌肉負荷。",
      heroImage: "assets/titans/biceps.webp", color: "#f6bd4a",
      tracks: {
        foundation: [
          { code: "G-F1", title: "支點之眼", summary: "辨認肘關節、肌肉拉力與石球重力。", mission: "石臂機關只有在三種角色被正確辨認後才會甦醒。", skill: "辨認常見作用力", prerequisites: "讀圖", time: "30–60 秒", image: "assets/titans/biceps.webp", visual: "pivot", known: ["前臂托住石球", "肘關節連接上臂與前臂", "石球受重力向下"], control: control("標記位置", 1, 2, 1, 2, 1, "號"), prediction: prediction("移動標記到肘關節後，它應被判定為哪一種角色？", "pivot", [["pivot","支點"],["effort","施力點"],["load","阻力點"]]), reason: reason("為什麼肘關節是支點？", "rotate", [["rotate","前臂繞它轉動"],["heavy","它最重"],["muscle","它會產生肌力"]]), explanation: "支點是物體轉動所繞的固定位置；在這個模型中，前臂繞肘關節轉動。", hint: "先找出姿勢改變時，哪個位置是旋轉中心。" },
          { code: "G-F2", title: "距離之力", summary: "同樣的力離支點越遠，轉動效果越明顯。", mission: "兩道石門使用相同推力，只有一種施力位置能更輕易轉動門軸。", skill: "比較力臂", prerequisites: "距離比較", time: "30–60 秒", image: "assets/titans/triceps.webp", visual: "lever-distance", known: ["兩次推力大小相同", "推力方向相同", "只改變施力點到支點的距離"], control: control("施力點距離", 10, 30, 10, 30, 5, "cm"), prediction: prediction("把施力點由 10 cm 移到 30 cm，轉動效果會如何？", "increase", [["increase","變大"],["same","不變"],["decrease","變小"]]), reason: reason("哪一項最能解釋觀察結果？", "farther", [["farther","同樣的力離支點更遠"],["mass","手臂質量增加"],["speed","推力速度一定變快"]]), explanation: "力的大小與方向不變時，作用位置離支點越遠，轉動效果越明顯。", hint: "想像推門時，你會推門把還是靠近鉸鏈的位置？" },
          { code: "G-F3", title: "方向之門", summary: "比較沿骨骼與接近垂直的施力方向。", mission: "古代肌索可以改變拉力方向；你要找出最能讓前臂轉動的方向。", skill: "質性判斷力的方向", prerequisites: "辨認夾角", time: "45–75 秒", image: "assets/titans/triceps.webp", visual: "force-direction", known: ["力的大小固定", "施力點固定", "只改變拉力方向"], control: control("拉力與前臂夾角", 15, 90, 15, 90, 15, "°"), prediction: prediction("夾角由 15° 接近 90°，轉動效果通常如何？", "increase", [["increase","變大"],["same","不變"],["decrease","變小"]]), reason: reason("關鍵原因是什麼？", "perpendicular", [["perpendicular","垂直於骨骼的分量變大"],["bone","骨骼會變長"],["weight","石球重量變小"]]), explanation: "同樣大小的力越接近垂直於力臂，越能造成轉動；沿著骨骼拉時多半只造成拉伸或壓縮。", hint: "把力想成可分成沿骨骼與垂直骨骼兩部分。" },
          { code: "G-F4", title: "省力姿勢", summary: "從距離與方向選出較省力的持物姿勢。", mission: "巨人必須搬運石球穿越長廊；選錯姿勢會讓肌肉過早疲勞。", skill: "整合距離與方向", prerequisites: "支點、力的方向", time: "45–90 秒", image: "assets/titans/deadlift.webp", visual: "posture", known: ["石球重量相同", "比較石球靠近與遠離身體", "肌肉必須抵抗石球造成的轉動"], control: control("石球離身體距離", 45, 15, 15, 45, 5, "cm"), prediction: prediction("把石球由離身體 45 cm 收近到 15 cm，肌肉負擔通常如何？", "decrease", [["decrease","減少"],["same","不變"],["increase","增加"]]), reason: reason("最直接的理由是什麼？", "shorter", [["shorter","重力到支點的距離縮短"],["lighter","石球質量變小"],["gravity","重力方向改變"]]), explanation: "把負重靠近支點可縮短重力力臂，因此肌肉需要抵抗的轉動效果較小。", hint: "負重沒有變輕，真正改變的是它到關節的距離。" }
        ],
        advanced: [
          { code: "G-A1", title: "二頭肌之力", summary: "以第三級槓桿求肌肉需要的拉力。", mission: "石球力矩必須由靠近肘部附著的二頭肌平衡。", skill: "力矩平衡", prerequisites: "代數、力矩", time: "60–120 秒", image: "assets/titans/biceps.webp", visual: "biceps", known: ["石球重力 50 N，距肘 30 cm", "二頭肌力臂 5.0 cm", "前臂靜止"], models: [option("balance","F肌 × 5 = 50 × 30"),option("force","F肌 = 50 N"),option("inverse","F肌 × 30 = 50 × 5")], correctModel: "balance", inputs: [input("force","二頭肌拉力","N",300,1)], explanation: "力矩平衡給出 F肌×5 = 50×30，因此二頭肌需提供 300 N。", hint: "支點取在肘關節，先比較肌肉與石球的力臂。" },
          { code: "G-A2", title: "三頭肌之謎", summary: "使用 150° 夾角計算石球重力。", mission: "過頭托球的封印採用畫面幾何：力臂向量與向下重力夾角為 150°。", skill: "τ = rF sinθ", prerequisites: "三角函數、力矩", time: "75–150 秒", image: "assets/titans/triceps.webp", visual: "triceps", known: ["三頭肌拉力 300 N", "三頭肌等效力臂 5.0 cm", "石球距肘 30 cm", "力臂向量與重力夾角 150°"], models: [option("sine","300×5 = W×30×sin150°"),option("cosine","300×5 = W×30×cos150°"),option("noangle","300×5 = W×30")], correctModel: "sine", inputs: [input("weight","石球重力","N",100,1)], explanation: "sin150°=0.5；300×5 = W×30×0.5，所以 W=100 N。", hint: "力矩使用力臂向量與力的夾角；sin150° 等於 sin30°。" },
          { code: "G-A3", title: "硬舉之重", summary: "整合上半身、石球與髖伸肌的多力矩平衡。", mission: "髖關節封印同時承受軀幹與石輪兩個外力矩。", skill: "多力矩平衡", prerequisites: "代數、力矩加總", time: "90–180 秒", image: "assets/titans/deadlift.webp", visual: "deadlift", known: ["上半身重力 300 N，力臂 40 cm", "石球重力 W，力臂 60 cm", "髖肌力 2250 N，力臂 8 cm"], models: [option("sum","2250×8 = 300×40 + W×60"),option("single","2250×8 = W×60"),option("subtract","2250×8 + 300×40 = W×60")], correctModel: "sum", inputs: [input("weight","石球重力","N",100,1)], explanation: "髖肌力矩 18000 N·cm 必須同時平衡軀幹 12000 N·cm 與石球力矩，因此 W=100 N。", hint: "不要漏掉上半身重量，它與石球對髖部造成同方向力矩。" },
          { code: "G-A4", title: "阿基里斯之踵", summary: "分解肌腱力並完成足部靜力平衡。", mission: "踮腳機關只有在阿基里斯腱對前腳掌支點的有效力矩正確時才會開啟。", skill: "分力與靜力平衡", prerequisites: "三角函數、力矩", time: "90–180 秒", image: "assets/titans/achilles.webp", visual: "achilles", known: ["肌腱張力 3000 N", "肌腱與腳板夾角 120°", "肌腱距前腳掌支點 1.0 cm", "身體重力作用線距支點 20 cm"], models: [option("perp","3000×sin120°×1 = W×20"),option("full","3000×1 = W×20"),option("cos","3000×cos120°×1 = W×20")], correctModel: "perp", inputs: [input("weight","身體重力","N",130,2)], explanation: "肌腱垂直分量約 2598 N；以足尖為支點平衡後 W≈2598/20≈130 N。", hint: "只有垂直於腳板的肌腱分量產生有效力矩。" }
        ]
      }
    },
    {
      id: "chrono", number: "02", eyebrow: "MOTION & GRAPHS", name: "時空軌跡修復者", short: "運動學",
      description: "從位置—時間圖判斷速度與相遇，再以運動方程修復追擊與煞車事件。",
      heroImage: "assets/chrono/time-1.webp", color: "#64d9ff",
      tracks: {
        foundation: [
          { code:"C-F1",title:"誰跑得快",summary:"位置—時間圖越陡，物體運動越快。",mission:"兩列時空列車留下不同斜率的軌跡；判斷哪一列更快。",skill:"判讀位置—時間圖",prerequisites:"座標圖",time:"30–60 秒",image:"assets/chrono/time-1.webp",visual:"xt-slope",known:["橫軸為時間","縱軸為位置","比較相同時間內位置改變"],control:control("青色軌跡陡峭度",1,3,1,3,1,"級"),prediction:prediction("青色軌跡變得更陡時，青色列車的速度如何？","increase",[["increase","變快"],["same","不變"],["decrease","變慢"]]),reason:reason("圖像證據是什麼？","more-position",[["more-position","相同時間內位置改變更多"],["higher","線畫得比較高所以質量大"],["color","青色代表高速"]]),explanation:"位置—時間圖的斜率代表速度；相同時間內位置改變越多，線越陡、速度越大。",hint:"固定一段相同的時間，比較兩條線上升多少。"},
          { code:"C-F2",title:"相遇之兆",summary:"兩條位置—時間軌跡的交點代表同時同地。",mission:"找出兩列車在時空圖上真正會合的訊號。",skill:"辨認圖線交點",prerequisites:"座標圖",time:"30–60 秒",image:"assets/chrono/time-2.webp",visual:"xt-meet",known:["兩條線描述兩列車的位置","同一橫座標代表同一時間","同一縱座標代表同一位置"],control:control("觀察時間",0,6,0,6,1,"s"),prediction:prediction("觀察時間移到兩條線交點時，兩列車發生什麼事？","meet",[["meet","同時到達同一位置"],["speed","速度一定相同"],["stop","同時停止"]]),reason:reason("為什麼交點表示相遇？","same-coordinates",[["same-coordinates","時間與位置座標都相同"],["same-slope","兩線斜率永遠相同"],["same-color","兩線顏色接近"]]),explanation:"圖線交點的橫、縱座標同時相同，代表兩物體在同一時刻位於同一位置。",hint:"相遇需要同時滿足『同一時間』與『同一位置』。"},
          { code:"C-F3",title:"追擊預言",summary:"後車速度必須較大，才可能縮短領先距離。",mission:"橙車已先行，青車必須選擇能逐漸追近的速度狀態。",skill:"質性相對運動",prerequisites:"快慢比較",time:"45–75 秒",image:"assets/chrono/time-3.webp",visual:"chase",known:["橙車在前方","兩車同方向","青車從後方追趕"],control:control("青車相對速度",0,2,0,2,1,"級"),prediction:prediction("當青車比橙車更快時，兩車距離如何變化？","decrease",[["decrease","逐漸縮短"],["same","保持不變"],["increase","逐漸增加"]]),reason:reason("關鍵原因是什麼？","relative",[["relative","後車每秒前進得更多"],["front","前車一定會停下"],["mass","後車質量較大"]]),explanation:"同方向運動時，後車速度較大才具有正的追近速度，兩車間距會逐漸縮短。",hint:"每經過一秒，比較兩車各自前進的距離。"},
          { code:"C-F4",title:"煞車曲線",summary:"辨認速度下降、停止與越過星門的圖像特徵。",mission:"列車必須在星門前讓速度降到零；選出正確的速度—時間軌跡。",skill:"判讀速度—時間圖",prerequisites:"圖形趨勢",time:"45–90 秒",image:"assets/chrono/time-4.webp",visual:"brake",known:["橫軸為時間","縱軸為速度","速度降到 0 代表停止"],control:control("煞車強度",1,3,1,3,1,"級"),prediction:prediction("煞車變強時，速度降到 0 所需時間如何？","decrease",[["decrease","縮短"],["same","不變"],["increase","拉長"]]),reason:reason("在速度—時間圖上會看到什麼？","steeper-down",[["steeper-down","下降線更陡並較早碰到 0"],["up","線向上升"],["flat","線保持水平"]]),explanation:"較強煞車使速度下降更快，因此速度—時間線向下更陡，也更早到達零。",hint:"先找出圖上代表停止的 v=0 水平軸。"}
        ],
        advanced: [
          { code:"C-A1",title:"等速會合",summary:"由距離與時間求維持會合所需速度。",mission:"青車必須在 20 秒後抵達 120 公尺外的事件點。",skill:"等速運動",prerequisites:"v=Δx/Δt",time:"60–100 秒",image:"assets/chrono/time-1.webp",visual:"chrono-uniform",known:["位移 120 m","允許時間 20 s","等速直線運動"],models:[option("uniform","v = Δx / Δt"),option("accel","Δx = ½at²"),option("momentum","p = mv")],correctModel:"uniform",inputs:[input("speed","列車速度","m/s",6,.05)],explanation:"v=120/20=6 m/s。",hint:"題目沒有加速資訊，使用等速位移關係。"},
          { code:"C-A2",title:"加速會合",summary:"由靜止出發的位移與時間求加速度。",mission:"青車由靜止穿越 100 公尺長的加速環廊，必須在 10 秒抵達。",skill:"等加速度",prerequisites:"x=v₀t+½at²",time:"75–130 秒",image:"assets/chrono/time-2.webp",visual:"chrono-accel",known:["初速 0 m/s","位移 100 m","時間 10 s","加速度固定"],models:[option("accel","x = ½at²"),option("uniform","x = vt"),option("energy","v² = 2ax，直接令 v=10")],correctModel:"accel",inputs:[input("acceleration","加速度","m/s²",2,.03)],explanation:"100=½×a×10²，所以 a=2 m/s²。",hint:"由靜止出發，初速項為零。"},
          { code:"C-A3",title:"延遲追擊",summary:"使用相對速度處理先行與延遲。",mission:"橙車以 4 m/s 先行 10 秒，青車再以 8 m/s 出發。",skill:"相對速度",prerequisites:"等速、代數",time:"75–140 秒",image:"assets/chrono/time-3.webp",visual:"chrono-delay",known:["橙車速度 4 m/s","橙車先行 10 s","青車速度 8 m/s"],models:[option("relative","t = 先行距離 / (8−4)"),option("sum","t = 先行距離 / (8+4)"),option("ignore","t = 先行距離 / 8")],correctModel:"relative",inputs:[input("time","青車出發後追上時間","s",10,.1)],explanation:"橙車先行 40 m，追近速度為 4 m/s，所以需 10 s。",hint:"先算領先距離，再用兩車速度差求追近時間。"},
          { code:"C-A4",title:"煞車收束",summary:"由初速與加速度求停止距離。",mission:"列車以 20 m/s 進入星門廊，固定減速度為 4 m/s²。",skill:"等加速度煞停",prerequisites:"v²=v₀²+2aΔx",time:"75–140 秒",image:"assets/chrono/time-4.webp",visual:"chrono-stop",known:["初速 20 m/s","末速 0 m/s","加速度 −4 m/s²"],models:[option("v2","0 = 20² + 2(−4)Δx"),option("linear","0 = 20 − 4Δx"),option("uniform","Δx = 20×4")],correctModel:"v2",inputs:[input("distance","煞停距離","m",50,.2)],explanation:"0=400−8Δx，因此煞停距離為 50 m。",hint:"時間未知，可選不含時間的等加速度公式。"}
        ]
      }
    },
    {
      id:"photo",number:"03",eyebrow:"PHOTOELECTRIC EFFECT",name:"古光神殿",short:"近代物理",description:"先破解頻率門檻與亮度迷思，再計算光子能量、截止電壓與粒子數。",heroImage:"assets/photo/light-1.webp",color:"#76a9ff",
      tracks:{
        foundation:[
          {code:"P-F1",title:"頻率門檻",summary:"頻率增加，單一光子能量增加。",mission:"調高光的頻率，判斷何時能越過金屬功函數門檻。",skill:"E 與 f 的比例",prerequisites:"比例概念",time:"30–60 秒",image:"assets/photo/light-1.webp",visual:"photo-threshold",known:["同一金屬的門檻固定","光子能量隨頻率增加","先不計算數值"],control:control("光的頻率",2,4,2,4,1,"級"),prediction:prediction("把頻率由低調高，單一光子能量如何？","increase",[["increase","增加"],["same","不變"],["decrease","減少"]]),reason:reason("能打出電子的必要條件是什麼？","threshold",[["threshold","單一光子能量超過功函數"],["bright","光只要夠亮"],["time","照射時間夠久一定可以"]]),explanation:"光電效應有頻率門檻；單一光子能量不足時，增加等待時間也不能把能量累積給同一電子。",hint:"關鍵是『每一顆光子』的能量，而不是總共有多少光。"},
          {code:"P-F2",title:"亮度迷霧",summary:"頻率不足時，再強的光也不能打出電子。",mission:"古光祭壇故意以極亮紅光誤導闖關者。",skill:"區分頻率與強度",prerequisites:"光子概念",time:"45–75 秒",image:"assets/photo/light-2.webp",visual:"photo-intensity",known:["光的頻率低於金屬門檻","只提高光強度","金屬種類不變"],control:control("光強度",1,5,1,5,1,"級"),prediction:prediction("頻率仍低於門檻，只把光變強，會打出電子嗎？","no",[["no","不會"],["yes","一定會"],["faster","只會讓電子更快"]]),reason:reason("為什麼？","per-photon",[["per-photon","每顆光子的能量仍不足"],["metal","金屬突然變重"],["voltage","電壓自動抵消"]]),explanation:"強度增加代表光子數增加，但每顆光子的能量由頻率決定；低於門檻仍無法逸出。",hint:"把強度想成光子『數量』，頻率想成每顆光子的『能量』。"},
          {code:"P-F3",title:"金屬之別",summary:"不同金屬具有不同的光電門檻。",mission:"用同一束光照射兩塊金屬，從實驗結果判斷哪一塊功函數較小。",skill:"由證據比較門檻",prerequisites:"控制變因",time:"45–75 秒",image:"assets/photo/light-3.webp",visual:"photo-metal",known:["照射頻率相同","A 金屬放出電子","B 金屬沒有放出電子"],control:control("照射測試",1,2,1,2,1,"次"),prediction:prediction("根據結果，哪一塊金屬較容易放出電子？","A",[["A","A 金屬"],["B","B 金屬"],["same","無法區分"]]),reason:reason("可以做出什麼判斷？","lower",[["lower","A 的功函數較小"],["higher","A 的功函數較大"],["mass","A 的質量較小"]]),explanation:"同頻率光下，能放出電子的 A 金屬門檻不高於該光子能量，因此相較 B 更容易放出電子。",hint:"控制相同照射條件，比較哪個金屬先產生反應。"},
          {code:"P-F4",title:"有限光能",summary:"選擇剛好越過門檻的頻率並合理分配強度。",mission:"三道光門共享有限能量；過低頻率無效，過高設定又浪費資源。",skill:"質性策略",prerequisites:"頻率門檻、強度",time:"60–90 秒",image:"assets/photo/light-4.webp",visual:"photo-budget",known:["三座金屬門檻不同","頻率必須先超過門檻","門檻已通過後，提高強度可增加電子數"],control:control("頻率設定",2,4,2,5,1,"級"),prediction:prediction("有限資源下，合理的第一步是什麼？","threshold-first",[["threshold-first","先選剛能越過門檻的頻率"],["intensity-only","全部能量只加強度"],["max","頻率與強度永遠都開最大"]]),reason:reason("越過門檻後，若需要更多電子應優先調整什麼？","intensity",[["intensity","增加光強度"],["lower-frequency","把頻率降回門檻以下"],["wait","只增加等待時間"]]),explanation:"策略是先確保單一光子能量足夠，再用強度控制有效光子數；這能把頻率與強度的角色分開。",hint:"先問『能不能打出』，再問『能打出多少』。"}
        ],
        advanced:[
          {code:"P-A1",title:"光子換算",summary:"由波長求單一光子能量。",mission:"藍光封印給定波長 400 nm，需換算成電子伏特。",skill:"E=hc/λ",prerequisites:"科學記號、單位換算",time:"60–120 秒",image:"assets/photo/light-1.webp",visual:"photo-energy",known:["λ=400 nm","可用 hc≈1240 eV·nm"],models:[option("lambda","E=1240/λ"),option("multiply","E=1240λ"),option("intensity","E=P×t")],correctModel:"lambda",inputs:[input("energy","光子能量","eV",3.10,.03)],explanation:"E≈1240/400=3.10 eV。",hint:"波長越短，單一光子能量越高。"},
          {code:"P-A2",title:"最大動能",summary:"由光子能量扣除金屬功函數。",mission:"能量 3.5 eV 的光子照射功函數 2.3 eV 的鈉。",skill:"光電方程",prerequisites:"能量守恆",time:"60–120 秒",image:"assets/photo/light-2.webp",visual:"photo-kmax",known:["Eγ=3.5 eV","Φ=2.3 eV","忽略其他損失"],models:[option("subtract","Kmax=Eγ−Φ"),option("add","Kmax=Eγ+Φ"),option("ratio","Kmax=Eγ/Φ")],correctModel:"subtract",inputs:[input("kmax","最大動能","eV",1.2,.02)],explanation:"Kmax=3.5−2.3=1.2 eV。",hint:"功函數是電子離開金屬表面必須支付的能量。"},
          {code:"P-A3",title:"截止電壓",summary:"由最大動能求停止光電子的電壓。",mission:"光電子最大動能為 1.4 eV，調整反向電壓剛好讓光電流歸零。",skill:"eVₛ=Kmax",prerequisites:"電位能、光電方程",time:"60–120 秒",image:"assets/photo/light-3.webp",visual:"photo-voltage",known:["Kmax=1.4 eV","1 eV 對應電子通過 1 V 的能量"],models:[option("stopping","eVₛ=Kmax"),option("square","eVₛ²=Kmax"),option("power","Vₛ=Kmax×光強")],correctModel:"stopping",inputs:[input("voltage","截止電壓","V",1.4,.02)],explanation:"以 eV 為能量單位時，1.4 eV 對應 1.4 V 的截止電壓。",hint:"截止電壓與最大動能有關，不由光強度決定。"},
          {code:"P-A4",title:"光束配給",summary:"計算光子流率、量子效率與有效電子數。",mission:"20 W 光束照射 2 秒；教學模型設定每瓦每秒 10 顆光子、量子效率 25%。",skill:"率與效率",prerequisites:"比例、百分率",time:"75–150 秒",image:"assets/photo/light-4.webp",visual:"photo-flux",known:["20 W","每 W 每秒 10 顆光子","照射 2 s","量子效率 25%"],models:[option("flux","Ne=P×10×t×η"),option("divide","Ne=P/(10tη)"),option("energy","Ne=光子能量−功函數")],correctModel:"flux",inputs:[input("electrons","有效電子數","顆",100,1)],explanation:"20×10×2×0.25=100 顆有效電子。這是明確標示的教學縮放模型。",hint:"先求入射光子總數，再乘量子效率。"}
        ]
      }
    },
    {
      id:"ripple",number:"04",eyebrow:"WAVES & INTERFERENCE",name:"水之神殿",short:"波動",description:"用可操作水面建立頻率、波長與振幅直覺，再進入相位、程差與節腹線計算。",heroImage:"assets/ripple/water-1.webp",color:"#55e2db",
      tracks:{
        foundation:[
          {code:"W-F1",title:"水之節奏",summary:"頻率變大時，波長變短、條紋變窄。",mission:"調高水眼振動頻率，預測同心波紋會如何改變。",skill:"頻率與波長質性關係",prerequisites:"讀圖、反比趨勢",time:"30–60 秒",image:"assets/ripple/water-1.webp",visual:"wave-frequency",known:["水波速度固定","單一波源","頻率由 2 Hz 調到 4 Hz"],control:control("頻率",2,4,1,5,.5,"Hz"),prediction:prediction("頻率由 2 Hz 增加到 4 Hz，環形條紋如何變化？","narrow",[["narrow","變窄、變密"],["same","不變"],["wide","變寬、變疏"]]),reason:reason("哪一個因果鏈正確？","inverse",[["inverse","波速固定，f 增加所以 λ 減少"],["amplitude","頻率增加所以振幅必定增加"],["speed","頻率增加所以水波速度必定增加"]]),explanation:"在同一介質且波速固定時，v=fλ；頻率增加，波長縮短，所以條紋變密。",hint:"固定波速，把 f 與 λ 看成互相補償的兩個量。"},
          {code:"W-F2",title:"振幅幻象",summary:"振幅增大會加強起伏與對比，但不改變波長。",mission:"提高水眼振幅，分辨『看起來更強』與『條紋間距改變』。",skill:"區分振幅與波長",prerequisites:"波形判讀",time:"30–60 秒",image:"assets/ripple/water-2.webp",visual:"wave-amplitude",known:["頻率固定","水波速度固定","振幅由 1 級增至 3 級"],control:control("振幅",1,3,1,3,.5,"級"),prediction:prediction("振幅增加後，波紋主要如何改變？","contrast",[["contrast","起伏與明暗對比變強"],["narrow","波長變短"],["faster","傳播速度必定增加"]]),reason:reason("為什麼條紋間距不變？","frequency",[["frequency","頻率與波速都沒改變"],["source","波源消失了"],["mass","水的質量變成零"]]),explanation:"振幅描述偏離平衡位置的程度；只改振幅不會改變由波速與頻率決定的波長。",hint:"把『波有多高』與『相鄰波峰隔多遠』分開看。"},
          {code:"W-F3",title:"雙源初醒",summary:"兩個同頻波源產生穩定的加強區與削弱區。",mission:"喚醒第二座水眼，觀察兩組波疊加後出現的新結構。",skill:"辨認干涉現象",prerequisites:"波的疊加概念",time:"45–75 秒",image:"assets/ripple/water-3.webp",visual:"wave-two-source",known:["兩波源頻率相同","兩波源持續振動","不計算相位差"],control:control("波源數量",1,2,1,2,1,"個"),prediction:prediction("由一個波源改成兩個同頻波源，水面會出現什麼？","bands",[["bands","穩定的加強與削弱區"],["nothing","完全沒有變化"],["stop","所有水波都消失"]]),reason:reason("這些區域形成的原因是什麼？","superpose",[["superpose","兩列波在各處疊加"],["gravity","重力忽然改變"],["boil","水溫升高"]]),explanation:"兩列同頻波重疊後，在不同位置持續加強或削弱，形成穩定干涉圖樣。",hint:"觀察哪些位置總是明顯起伏，哪些位置長期接近平靜。"},
          {code:"W-F4",title:"雙源之謎",summary:"波源間距增加時，節線與腹線分布通常變密。",mission:"頻率固定，只拉開兩座水眼，匹配更密集的干涉骨架。",skill:"波源間距與圖樣",prerequisites:"干涉現象",time:"45–90 秒",image:"assets/ripple/water-4.webp",visual:"wave-separation",known:["頻率固定","兩波源同頻","間距由 4 格增至 8 格"],control:control("波源間距",4,8,3,10,.5,"格"),prediction:prediction("波源距離增加後，節線／腹線分布通常如何？","denser",[["denser","變得較密"],["same","完全不變"],["none","全部消失"]]),reason:reason("同時有哪一項保持不變？","wavelength",[["wavelength","單一波源的波長"],["geometry","干涉圖幾何"],["source-distance","波源距離"]]),explanation:"頻率與介質不變，所以單一波源波長不變；增加波源間距則讓可出現的程差範圍變大，干涉線數通常增加。",hint:"分開觀察『每一圈的間距』與『兩組圓相交形成的骨架』。"}
        ],
        advanced:[
          {code:"W-A1",title:"波速石碑",summary:"使用 v=fλ 求波速。",mission:"水眼頻率為 6 Hz，相鄰波峰距離為 0.50 m。",skill:"v=fλ",prerequisites:"代數、單位",time:"60–100 秒",image:"assets/ripple/water-1.webp",visual:"wave-calc",known:["f=6 Hz","λ=0.50 m"],models:[option("wave","v=fλ"),option("divide","v=f/λ"),option("square","v=fλ²")],correctModel:"wave",inputs:[input("speed","波速","m/s",3,.03)],explanation:"v=6×0.50=3.0 m/s。",hint:"Hz 是每秒振動次數，乘上一個波長就是每秒傳播距離。"},
          {code:"W-A2",title:"相位與程差之門",summary:"由程差判斷相對相位與破壞性干涉。",mission:"某觀測點到兩個同相波源的程差為 1.5λ。",skill:"程差與相位",prerequisites:"相位、波的疊加",time:"75–140 秒",image:"assets/ripple/water-2.webp",visual:"wave-phase",known:["兩波源同相","Δr=1.5λ","相位差以 360° 為一週期"],models:[option("phase","Δφ=360°×Δr/λ"),option("linear","Δφ=180°×Δr/λ"),option("none","程差不影響相位")],correctModel:"phase",inputs:[input("phase","等效相位差","°",180,1)],explanation:"1.5λ 對應 540°，扣除一個 360° 週期後為 180°，因此為破壞性干涉。",hint:"相位差可相差整數個 360°；最後取等效角。"},
          {code:"W-A3",title:"節腹線計數",summary:"由 d/λ 計算完整平面的節線與腹線。",mission:"兩個同相點波源間距 d=3.2λ；計算左右兩側都包含的完整圖樣。",skill:"干涉線階數",prerequisites:"程差、取整數",time:"90–160 秒",image:"assets/ripple/water-3.webp",visual:"wave-lines",known:["d/λ=3.2","波源同相","計完整平面、左右對稱線都算","非整數與半整數邊界"],models:[option("count","腹線 2⌊d/λ⌋+1；節線 2⌊d/λ+1/2⌋"),option("swap","腹線 2⌊d/λ+1/2⌋；節線 2⌊d/λ⌋+1"),option("round","兩者都取最接近整數")],correctModel:"count",inputs:[input("antinodes","腹線條數","條",7,0),input("nodes","節線條數","條",6,0)],explanation:"腹線階數 m=0,±1,±2,±3，共 7 條；節線程差 0.5λ、1.5λ、2.5λ，各有左右兩側，共 6 條。",hint:"先列出允許的程差階數，再把中央線與左右對稱分開計數。"},
          {code:"W-A4",title:"干涉核心",summary:"從圖形證據反推頻率與中央相位。",mission:"水波速度 12 cm/s，圖上相鄰波峰距離 4 cm，中央線為節線。",skill:"反推多個參數",prerequisites:"v=fλ、相位",time:"90–180 秒",image:"assets/ripple/water-4.webp",visual:"wave-inverse",known:["v=12 cm/s","λ=4 cm","兩波源振幅相同","中央線為節線"],models:[option("inverse","f=v/λ，中央節線代表兩源反相"),option("multiply","f=vλ，中央節線代表同相"),option("amplitude","f 由振幅決定")],correctModel:"inverse",inputs:[input("frequency","頻率","Hz",3,.03),input("phase","兩源相位差","°",180,1)],explanation:"f=12/4=3 Hz；中央點到兩源等距，卻是節線，表示兩源相差 180°。",hint:"中央線程差為零；若仍相消，差異只能來自波源初相位。"}
        ]
      }
    },
    {
      id:"uncertainty",number:"05",eyebrow:"MEASUREMENT & EVIDENCE",name:"不確定度神殿",short:"實驗與量測",description:"從刻度、散布與誠實紀錄建立量測素養，再完成組合不確定度與導出量證據鏈。",heroImage:"assets/uncertainty/measure-1.webp",color:"#c3a6ff",
      tracks:{
        foundation:[
          {code:"U-F1",title:"刻度之眼",summary:"讀取儀器數值、單位與最小刻度。",mission:"電子秤穩定顯示 63 g；不要宣稱儀器沒有提供的位數。",skill:"儀器判讀",prerequisites:"單位",time:"30–60 秒",image:"assets/uncertainty/measure-1.webp",visual:"measure-scale",known:["電子秤顯示 63 g","最小顯示單位 1 g","多次讀值相同"],control:control("顯示位數",0,1,0,2,1,"級"),prediction:prediction("哪一筆直接讀值最恰當？","63g",[["63g","63 g"],["63.000g","63.000 g"],["about","約 60 g"]]),reason:reason("為什麼不能寫成 63.000 g？","digits",[["digits","儀器沒有提供那些小數位"],["mass","木塊太輕"],["unit","g 不是單位"]]),explanation:"紀錄應保留儀器實際提供的位數與單位；多寫小數會過度宣稱精度。",hint:"螢幕上實際出現了幾位數？"},
          {code:"U-F2",title:"重複回聲",summary:"量測散布不等於實驗失敗。",mission:"比較兩組重複量測，判斷哪一組的重複性較好。",skill:"辨認散布",prerequisites:"大小比較",time:"30–60 秒",image:"assets/uncertainty/measure-2.webp",visual:"measure-scatter",known:["A 組：25.6、25.6、25.7、25.6","B 組：25.1、25.8、25.4、26.0","使用同一單位"],control:control("顯示資料組",1,2,1,2,1,"組"),prediction:prediction("哪一組量測結果較集中？","A",[["A","A 組"],["B","B 組"],["same","兩組完全相同"]]),reason:reason("較集中的結果代表什麼？","repeatability",[["repeatability","重複性較好"],["truth","一定等於真值"],["zero","不確定度必定為零"]]),explanation:"散布較小表示在相同條件下重複性較好，但仍不能單憑集中就保證沒有系統誤差。",hint:"比較每組最大值與最小值相差多少。"},
          {code:"U-F3",title:"哪把尺更適合",summary:"依任務需求選擇合適的最小刻度。",mission:"要量測約 25.6 mm 的小銅柱，選擇公分尺或 0.1 mm 游標尺。",skill:"選擇量具",prerequisites:"刻度與單位",time:"30–60 秒",image:"assets/uncertainty/measure-3.webp",visual:"measure-tool",known:["需要分辨約 0.1 mm 的差異","公分尺最小刻度 1 mm","游標尺可讀到 0.1 mm"],control:control("所需解析度",1,2,1,2,1,"級"),prediction:prediction("哪一件量具較符合任務？","caliper",[["caliper","0.1 mm 游標尺"],["ruler","1 mm 公分尺"],["either","兩者完全相同"]]),reason:reason("選擇依據是什麼？","resolution",[["resolution","最小刻度能分辨所需差異"],["color","量具顏色較深"],["length","量具本身較重"]]),explanation:"量具解析度必須足以分辨任務關心的差異；更細刻度不代表永遠更好，但此任務確實需要 0.1 mm。",hint:"先問你希望分辨到多小，再比較儀器刻度。"},
          {code:"U-F4",title:"誠實的數字",summary:"選出不過度宣稱精度的量測報告。",mission:"平均高度約 25.625 mm，估計不確定度約 0.09 mm；選出位數一致的表達。",skill:"量測結果表達",prerequisites:"小數位",time:"45–75 秒",image:"assets/uncertainty/measure-4.webp",visual:"measure-report",known:["平均值計算結果 25.625 mm","不確定度約 0.09 mm","數值與不確定度小數位應一致"],control:control("報告格式",1,2,1,2,1,"式"),prediction:prediction("哪一種寫法最合適？","honest",[["honest","(25.63 ± 0.09) mm"],["precise","(25.625000 ± 0.09) mm"],["rough","(26 ± 0.0001) mm"]]),reason:reason("為什麼平均值寫到小數點後兩位？","place",[["place","與不確定度的末位對齊"],["pretty","看起來比較整齊"],["unit","因為 mm 只能有兩位"]]),explanation:"測量值與不確定度的末位應對齊，避免保留沒有意義的額外數字。",hint:"先看不確定度最後一位落在哪個小數位。"}
        ],
        advanced:[
          {code:"U-A1",title:"質量的密碼",summary:"由電子秤最小顯示單位估計 B 類標準不確定度。",mission:"電子秤顯示 63 g，最小顯示單位為 1 g，採均勻分布模型。",skill:"B 類不確定度",prerequisites:"有效數字、平方根",time:"75–130 秒",image:"assets/uncertainty/measure-1.webp",visual:"uncertainty-mass",known:["讀值 63 g","最小顯示單位 1 g","uB=LC/√12"],models:[option("rect","uB=1/√12"),option("half","uB=1/2"),option("zero","重複相同所以 u=0")],correctModel:"rect",inputs:[input("uncertainty","標準不確定度","g",.29,.015)],explanation:"uB=1/√12≈0.29 g；重複顯示相同不代表儀器解析度造成的不確定度為零。",hint:"數位顯示採寬度為一個最小顯示單位的均勻分布。"},
          {code:"U-A2",title:"三維尺寸",summary:"把尺的解析度轉成長度標準不確定度。",mission:"以最小刻度 0.1 cm 的量具量得長度 10.0 cm。",skill:"儀器不確定度",prerequisites:"B 類不確定度",time:"60–120 秒",image:"assets/uncertainty/measure-2.webp",visual:"uncertainty-dimension",known:["L=10.0 cm","最小刻度 0.1 cm","採均勻分布"],models:[option("rect","uL=0.1/√12"),option("full","uL=0.1"),option("percent","uL=10%")],correctModel:"rect",inputs:[input("uncertainty","長度標準不確定度","cm",.029,.002)],explanation:"uL=0.1/√12≈0.029 cm。",hint:"先確認公式中的 LC 使用和答案相同的 cm 單位。"},
          {code:"U-A3",title:"周長迴廊",summary:"處理加減與常數倍的不確定度傳遞。",mission:"矩形長 10.0±0.03 cm、寬 5.0±0.03 cm，求 P=2(L+W) 的標準不確定度。",skill:"加減法傳遞",prerequisites:"平方和開根號",time:"90–160 秒",image:"assets/uncertainty/measure-3.webp",visual:"uncertainty-perimeter",known:["uL=0.03 cm","uW=0.03 cm","L、W 獨立","P=2(L+W)"],models:[option("rss","uP=2√(uL²+uW²)"),option("linear","uP=2(uL+uW)"),option("relative","uP/P=uL/L+uW/W")],correctModel:"rss",inputs:[input("uncertainty","周長標準不確定度","cm",.085,.004)],explanation:"uP=2√(0.03²+0.03²)≈0.085 cm。",hint:"獨立不確定度先平方相加，再開根號；外面的常數 2 一起乘上。"},
          {code:"U-A4",title:"體積與密度核心",summary:"使用相對不確定度傳遞處理乘除。",mission:"木塊 10.0×5.0×2.0 cm，各邊 u=0.03 cm；質量 270 g，um=0.29 g。",skill:"導出量不確定度",prerequisites:"相對不確定度、平方和",time:"120–180 秒",image:"assets/uncertainty/measure-4.webp",visual:"uncertainty-density",known:["V=LWH","ρ=m/V","各來源獨立","標準不確定度以平方和組合"],models:[option("relative","(uρ/ρ)²=(um/m)²+(uV/V)²"),option("absolute","uρ=um−uV"),option("linear","uρ/ρ=um/m+uL/L+uW/W+uH/H")],correctModel:"relative",inputs:[input("density","密度","g/cm³",2.70,.015),input("uncertainty","密度標準不確定度","g/cm³",.045,.004)],explanation:"V=100 cm³，ρ=2.70 g/cm³；組合各相對不確定度後 uρ≈0.045 g/cm³。",hint:"乘除問題先把每個來源換成相對不確定度，再用平方和組合。"},
          {code:"U-A5",title:"銅柱回聲",summary:"組合重複量測 A 類與儀器 B 類不確定度。",mission:"四次高度為 25.40、25.70、25.80、25.60 mm；儀器最小顯示單位 0.1 mm。",skill:"A、B 類組合",prerequisites:"平均、樣本標準差",time:"120–180 秒",image:"assets/uncertainty/measure-5.webp",visual:"uncertainty-repeat",known:["平均值 25.625 mm","uA=s/√n","uB=0.1/√12 mm","uc=√(uA²+uB²)"],models:[option("combine","uc=√(uA²+uB²)"),option("add","uc=uA+uB"),option("onlyB","uc=uB")],correctModel:"combine",inputs:[input("mean","報告平均值","mm",25.63,.015),input("uncertainty","組合標準不確定度","mm",.09,.012)],explanation:"uA≈0.085 mm、uB≈0.029 mm，組合後 uc≈0.090 mm；報告為 (25.63±0.09) mm。",hint:"A、B 類都不可漏掉，且最終平均值小數位要與不確定度對齊。"}
        ]
      }
    }
  ];

  const totals = temples.reduce((acc, temple) => {
    acc.foundation += temple.tracks.foundation.length;
    acc.advanced += temple.tracks.advanced.length;
    return acc;
  }, { foundation: 0, advanced: 0 });

  return {
    version: "3.0.0",
    tracks: {
      foundation: { label: "初階殿", grade: "高一必修適合", task: "觀念・質性判斷", ability: "讀圖、比較、簡單比例", duration: "30–90 秒" },
      advanced: { label: "進階殿", grade: "高二／高三選修適合", task: "模型・計算挑戰", ability: "代數、向量、三角函數或有效數字", duration: "60–180 秒" }
    },
    totals,
    temples
  };
});
